Make remove-* No-CA compatible; Assign TLS-Crypt-V2 server key serial
Make No-CA compatible: remove-inline, remove-tlskey

Assign fixed values for TLS-Crypt-V2 server key serial numbers:
Hash-algo: SHA1 -> cv2_Srv_Serial='40x 0'
Hash-algo: SHA256 -> cv2_Srv_Serial='64x 0'

Correct regexp for tlskey_verify_in_use ()

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -361,7 +361,7 @@ Easy-TLS abbreviations:
   build-tls-crypt               - btc
   build-tls-crypt-v2-server     - btv2s | btcv2s
   build-tls-crypt-v2-client     - btv2c | btcv2c
-  remove-tlskey                 - No abbreviation
+  remove-tlskey                 - rt | rk
   save-id                       - sid
 
   status                        - s
@@ -375,7 +375,7 @@ Easy-TLS abbreviations:
   inline-tls-auth               - ita
   inline-tls-crypt              - itc
   inline-tls-crypt-v2           - itv2 | itcv2
-  remove-inline                 - No abbreviation
+  remove-inline                 - ri
   inline-show                   - is
   inline-index-rebuild          - No abbreviation
   inline-expire                 - ix
@@ -898,11 +898,13 @@ config_use ()
 	fixed_hash=1111111111111111111111111111111111111111
 	fixed_length=40
 	forbidden_hash=adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
+	cv2_Srv_Serial=0000000000000000000000000000000000000000
 	;;
 	SHA256)
 	fixed_hash=2222222222222222222222222222222222222222222222222222222222222222
 	fixed_length=64
 	forbidden_hash=01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
+	cv2_Srv_Serial=0000000000000000000000000000000000000000000000000000000000000000
 	;;
 	*)
 		error_msg "verify_hash - Unknown algorithm: ${EASYTLS_HASH_ALGO}"
@@ -2477,13 +2479,13 @@ verify_cert_serial ()
 	# https://github.com/TinCanTech/easy-tls/issues/158
 	case ${EASYRSA_RAND_SN} in
 	yes)
-		[ $serial_size -lt 33 ] || {
+		[ $serial_size -lt 41 ] || {
 			error_msg "verify_cert_serial - cert_serial size !<33: $cert_serial"
 			return 1
 			}
 	;;
 	no)
-		[ $serial_size -lt 33 ] || {
+		[ $serial_size -lt 41 ] || {
 			error_msg "verify_cert_serial - cert_serial size !<33: $cert_serial"
 			return 1
 			}
@@ -2529,7 +2531,9 @@ verify_tlskey_serial ()
 # # Verify that this key is no longer in use
 tlskey_verify_in_use ()
 {
-	"$EASYTLS_GREP" -q "^.*[[:blank:]]${tlskey_serial}$" "$EASYTLS_INLINE_INDEX"
+	x509_patt=".*[[:blank:]]${cert_serial}[[:blank:]]"
+	tlsk_patt=".*[[:blank:]]${tlskey_serial}"
+	"$EASYTLS_GREP" -q "^${x509_patt}${tlsk_patt}$" "$EASYTLS_INLINE_INDEX"
 } # => tlskey_verify_in_use ()
 
 # Remove a TLS-Crypt-V2 Client key and update the tlskey-index
@@ -2538,7 +2542,13 @@ remove_tlskey ()
 	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
 
 	name="$1"
-	cert_file="$EASYRSA_PKI/issued/$name.crt"
+	if [ $EASYTLS_NO_CA ]
+	then
+		cert_file="$EASYTLS_PKI/$name.crt"
+	else
+		cert_file="$EASYRSA_PKI/issued/$name.crt"
+	fi
+
 	tlskey_file="$EASYTLS_PKI/$name-tls-crypt-v2.key"
 	metadata_file="$EASYTLS_MD_DIR/$name-tls-crypt-v2.metadata"
 
@@ -3130,7 +3140,7 @@ inline_tls_crypt_v2 ()
 	else
 		# Must be a server
 		no_metadata=1
-		tlskey_serial='0000000000000000000000000000000000000000'
+		tlskey_serial="${cv2_Srv_Serial}"
 	fi
 
 	# Inline base file
@@ -3286,7 +3296,7 @@ build_tls_crypt_v2_server ()
 		die "Failed to create tls-crypt-v2-server key: $tlskey_file"
 
 	# Save incomplete server record to key-index
-	tlskey_serial='0000000000000000000000000000000000000000'
+	tlskey_serial="${cv2_Srv_Serial}"
 	cli_name="$srv_name" # Improve this
 	tlskey_index_update add || die "Failed to update tlskey-index"
 
@@ -6473,6 +6483,16 @@ case "$cmd" in
 				die "Error: inline_show"
 			cmd='Done'
 		;;
+		ri|remove-inline)
+			remove_inline "$@" || \
+				die "Error: remove_inline"
+			cmd='Done'
+		;;
+		rt|rk|remove-tlskey)
+			remove_tlskey "$@" || \
+				die "Error: remove_tlskey"
+			cmd='Done'
+		;;
 		d|disable)
 			disabled_list_manager "disable" "$@" || \
 				die "Error: disabled_list_manager"
@@ -6537,10 +6557,6 @@ case "$cmd" in
 		interactive_remove || \
 			die "Error: interactive_remove"
 		;;
-	remove-tlskey)
-		remove_tlskey "$@" || \
-			die "Error: remove_tlskey"
-		;;
 	sid|save-id)
 		save_id || \
 			die "Error: save_id"
@@ -6549,10 +6565,6 @@ case "$cmd" in
 		status "$@" || \
 			die "Error: status"
 		unset status_disabled_auto_check
-		;;
-	remove-inline)
-		remove_inline "$@" || \
-			die "Error: remove_inline"
 		;;
 	irn|irw|inline-renew)
 		inline_renew "$@" || \
