Introduce fingerprint sharing function: inline_share_fingerprint ()
Only available when using No CA mode.

When creating a client inline file it is now possible to specify the
server commonName and share the fingerprints:

* The server fingerprint is added to the client inline file.
* The client fingerprint is added to a list of fingerprints in the
  server inline file.

Use: -r|--ss-peer-finferprint=<Server_commonName>

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -77,6 +77,7 @@ Use the 'help' command above to get full usage details.
   inline    :Inter-active menu to build Inline files
   remove    :Inter-active menu to remove TLS keys and Inline files
   script    :Inter-active menu to configure Server scripts
+  selfsign  :Inter-active menu to build and inline self-signed certificates
   self-sign-server
   self-sign-client
   build-tls-auth
@@ -134,8 +135,9 @@ cmd_help()
 
         no-ca - Do not use an Easy-RSA Certificate Authority [CA].
         * Note: No-CA mode still requires use of './easyrsa init-pki'" ;;
-		build|inline|remove|script) text="
-  Inter-active menus to build, inline, remove and config various Easy-TLS files" ;;
+		build|inline|remove|script|selfsign) text="
+  Inter-active menus to build, inline, remove
+  and configure various Easy-TLS files" ;;
 		bta|build-tls-auth) text="
   build-tls-auth
       Create an OpenVPN TLS auth PSK (tls-auth.key)" ;;
@@ -285,10 +287,12 @@ cmd_help()
         * DISABLED *" ;;
 		sss|self-sign-server) text="
   self-sign-server
-       Build a self signed server certificate and key." ;;
+       Build a self signed server certificate and key.
+       Also see 'help options' for: -r|--ss-peer-fingerprint=<CommonName>" ;;
 		ssc|self-sign-client) text="
   self-sign-client
-       Build a self signed client certificate and key." ;;
+       Build a self signed client certificate and key.
+       Also see 'help options' for: -r|--ss-peer-fingerprint=<CommonName>" ;;
 
 		options)
 			opt_usage ;;
@@ -359,6 +363,13 @@ General options:
 -c|--ss-eccurve=<CURVE_NAME>
                     Specify an alternate Eliptic Curve for a self-signed key.
                     (Default: secp384r1)
+
+-r|--ss-peer-fingerprint=<CommonName>
+
+      When inlining a self-signed client certificate, specify the commonName
+      of the server certificate to share fingerprints of each node.
+      The fingerprint of the server will be added to the client inline file
+      and the fingerprint of the client will be added to the server inline file.
 
 -t|--tmp-dir=<DIR>     Temp directory where server-scripts write data.
                        Default: *nix /tmp/easytls
@@ -510,7 +521,7 @@ missing_file ()
 fatal_opt ()
 {
 	[ -z "${1}" ] && [ -n "${fatal_msg}" ] && die "${fatal_msg}"
-	fatal_msg="${fatal_msg}
+	[ -z "${1}" ] || fatal_msg="${fatal_msg}
 ${1}"
 }
 
@@ -1159,7 +1170,7 @@ verify_tls_init ()
 init_tls ()
 {
 	# Easy-TLS requires that your Easy-RSA PKI is initialised
-	verify_pki_init
+	[ $EASYTLS_NO_CA ] || verify_pki_init
 
 	# If EASYTLS_PKI exists, confirm before we remove
 	# skipped with EASYTLS_BATCH
@@ -1170,8 +1181,34 @@ WARNING!!!
 You are about to remove the EASYTLS_PKI at: ${EASYTLS_PKI}
 and initialize a fresh TLS PKI here."
 		# now remove it:
+		exec 6<&-
 		"${EASYTLS_RM}" -rf "${EASYTLS_PKI}" \
 		|| die "Removal of TLS dir failed. Check/correct errors above"
+	fi
+
+	# Create easytls dir in EasyRSA-PKI dir
+	"${EASYTLS_MKDIR}" -p "${EASYTLS_PKI}" || \
+		die "Failed to create easytls dir"
+
+	# Create data dir in easytls dir
+	"${EASYTLS_MKDIR}" -p "${EASYTLS_DATA_DIR}" || \
+		die "Failed to create data dir"
+
+	# Create lock-file
+	if [ -d "${EASYTLS_DATA_DIR}" ]
+	then
+		(	exec 2>/dev/null
+			set -o noclobber
+			exec 6> "${EASYTLS_TEMP_LOCK}" || return 1
+			printf "%s" "$$" >&6 || return 1
+		) || die "write lock-file"
+		exec 6< "${EASYTLS_TEMP_LOCK}" || die "read lock-file"
+		read -r <&6 EASYTLS_lock_PID
+		[ $$ -eq ${EASYTLS_lock_PID} ] || \
+			die "PID mismatch: $$ ${EASYTLS_lock_PID}"
+	else
+		# Easy-TLS is not initialised
+		:
 	fi
 
 	while [ -n "${1}" ]; do
@@ -1185,14 +1222,6 @@ and initialize a fresh TLS PKI here."
 
 	# Explicitly set EASYTLS_HASH_ALGO here
 	EASYTLS_HASH_ALGO="${EASYTLS_HASH_ALGO:-SHA256}"
-
-	# Create easytls dir in EasyRSA-PKI dir
-	"${EASYTLS_MKDIR}" -p "${EASYTLS_PKI}" || \
-		die "Failed to create easytls dir"
-
-	# Create data dir in easytls dir
-	"${EASYTLS_MKDIR}" -p "${EASYTLS_DATA_DIR}" || \
-		die "Failed to create data dir"
 
 	# Create metadata dir in easytls dir
 	"${EASYTLS_MKDIR}" -p "${EASYTLS_MD_DIR}" || \
@@ -1299,8 +1328,8 @@ and initialize a fresh TLS PKI here."
 			"    *nix    - /var/easytls (Create with sudo)"
 		print \
 			"    systemd - /tmp (Use systemd unit file openvpn-server@.service)"
-		print
 	fi
+	print
 } # => init_tls ()
 
 # Auto-check for invalid inline files
@@ -3474,6 +3503,8 @@ inline_tls_auth ()
 	# Hash inline file and add hash to index
 	inline_index_update add || die "Failed to update inline-index"
 
+	inline_share_fingerprint "${name}" || die "Failed to share fingerprint"
+
 	notice "Inline TLS auth file created: ${inline_file}"
 	easytls_verbose
 } # => inline_tls_auth ()
@@ -3530,6 +3561,8 @@ inline_tls_crypt_v1 ()
 
 	# Hash inline file and add hash to index
 	inline_index_update add || die "Failed to update inline-index"
+
+	inline_share_fingerprint "${name}" || die "Failed to share fingerprint"
 
 	notice "Inline TLS crypt file created: ${inline_file}"
 	easytls_verbose
@@ -3730,9 +3763,154 @@ inline_tls_crypt_v2 ()
 	# Hash inline file and add hash to index
 	inline_index_update add || die "Failed to update inline-index"
 
+	inline_share_fingerprint "${name}" || die "Failed to share fingerprint"
+
 	notice "Inline TLS crypt v2 file created: ${inline_file}"
 	easytls_verbose
 } # => inline_tls_crypt_v2 ()
+
+# Share peer fingerprints
+inline_share_fingerprint ()
+{
+	if [ $EASYTLS_NO_CA ] && [ -n "${EASYTLS_PEER_FPR}" ] && \
+		[ "${cert_purpose}" = "Client" ]
+	then
+		# Do it
+		:
+	else
+		# Don't do it
+		easytls_verbose "Not sharing fingerprint to peer!"
+		return 0
+	fi
+
+	[ $# -ge 1 ] || die "Required option: client commonName"
+
+	# Client setup
+	cli_name="${1}"
+	cli_cert="${EASYTLS_PKI}/${cli_name}.crt"
+	[ -f "${cli_cert}" ] || \
+		missing_file "inline_share_fingerprint - ${cli_cert}"
+	cli_inline="${EASYTLS_PKI}/${cli_name}.inline"
+	cli_fp_list="${EASYTLS_PKI}/${cli_name}.pfp-list"
+	# Set TLSKEY_SUBNAME names
+	sub_name="${name}-${TLSKEY_SUBNAME}"
+	[ "${TLSKEY_SUBNAME}" = 'NOSUBKEY' ] || {
+		cli_inline="${EASYTLS_PKI}/${sub_name}.inline"
+		cli_fp_list="${EASYTLS_PKI}/${sub_name}.pfp-list"
+		}
+	[ -f "${cli_inline}" ] || \
+		missing_file "inline_share_fingerprint - ${cli_inline}"
+	cli_fpr="$(openssl_generate_fingerprint "${cli_cert}")" || {
+		error_msg "cli_fpr"
+		return 1
+		}
+	cli_fpr="${cli_fpr##*=}"
+
+	# Server setup
+	srv_name="${EASYTLS_PEER_FPR}"
+	srv_cert="${EASYTLS_PKI}/${srv_name}.crt"
+	[ -f "${srv_cert}" ] || \
+		missing_file "inline_share_fingerprint - ${srv_cert}"
+	srv_inline="${EASYTLS_PKI}/${srv_name}.inline"
+	[ -f "${srv_inline}" ] || \
+		missing_file "inline_share_fingerprint - ${srv_inline}"
+	srv_fp_list="${EASYTLS_PKI}/${srv_name}.pfp-list"
+	srv_fpr="$(openssl_generate_fingerprint "${srv_cert}")" || {
+		error_msg "srv_fpr"
+		return 1
+		}
+	srv_fpr="${srv_fpr##*=}"
+
+	# fingerprint pattern
+	fpr_tplt=""
+	i=1
+	while [ $i -lt 32 ]
+	do
+		fpr_tplt="${fpr_tplt}..:"
+		i=$((i+1))
+	done
+	fpr_tplt="${fpr_tplt}.."
+
+	# Remove node from inline index
+	generate_and_validate_file_hash "${cli_inline}" verified_inline_hash || {
+		error_msg "inline_share_fingerprint - generate_and_validate_file_hash"
+		error_msg "${cli_inline}"
+		return 1
+		}
+
+	known_inline_hash=${verified_inline_hash}
+	inline_serial="$(inline_index_ilhash_to_serial)"
+	inline_index_update del || die "Failed to update inline-index"
+
+	# Give server name and FP to client
+	{	print "# Peer-Server ${srv_name}"
+		print "${srv_fpr}"
+	} > "${cli_fp_list}-temp"
+	"${EASYTLS_MV}" -f "${cli_fp_list}-temp" "${cli_fp_list}"
+
+	# Delete existing
+	"${EASYTLS_SED}" -i -e "\\\^<peer-fingerprint>\$\\d" \
+		-e "\\\^#[[:blank:]]Peer-Server.*\$\\d" -e "\\\^${fpr_tplt}\$\\d" \
+		-e "\\\^</peer-fingerprint>\$\\d" "${cli_inline}"
+
+	# Append new
+	{	"${EASYTLS_CAT}" "${cli_inline}"
+		print "<peer-fingerprint>"
+		"${EASYTLS_CAT}" "${cli_fp_list}"
+		print "</peer-fingerprint>"
+	} > "${cli_inline}-temp"
+	"${EASYTLS_MV}" -f "${cli_inline}-temp" "${cli_inline}"
+
+	# Add node to inline-index
+	name="${cli_name}"
+	inline_file="${cli_inline}"
+	inline_index_update add || die "Failed to update inline-index"
+
+	# Remove node from inline-index
+	generate_and_validate_file_hash "${srv_inline}" verified_inline_hash || {
+		error_msg "inline_share_fingerprint - generate_and_validate_file_hash"
+		error_msg "${srv_inline}"
+		return 1
+		}
+
+	known_inline_hash=${verified_inline_hash}
+	inline_serial="$(inline_index_ilhash_to_serial)"
+	inline_index_update del || die "Failed to update inline-index"
+
+	# Add client name and FP to server FP list
+	if [ -f "${srv_fp_list}" ] && \
+		"${EASYTLS_GREP}" -q "${cli_fpr}" "${srv_fp_list}"
+	then
+		# Fingerprint is already added
+		:
+	else
+		{	[ -f "${srv_fp_list}" ] && "${EASYTLS_CAT}" "${srv_fp_list}"
+			print "# Peer-Client ${cli_name}"
+			print "${cli_fpr}"
+		} > "${srv_fp_list}-temp"
+		"${EASYTLS_MV}" -f "${srv_fp_list}-temp" "${srv_fp_list}"
+	fi
+
+	# Update server peer-fingerprint list in inline-file
+	# Delete existing
+	"${EASYTLS_SED}" -i -e "\\\^<peer-fingerprint>\$\\d" \
+		-e "\\\^#[[:blank:]]Peer-Client.*\$\\d" -e "\\\^${fpr_tplt}\$\\d" \
+		-e "\\\^</peer-fingerprint>\$\\d" "${srv_inline}"
+	# Append new
+	{	"${EASYTLS_CAT}" "${srv_inline}"
+		print "<peer-fingerprint>"
+		"${EASYTLS_CAT}" "${srv_fp_list}"
+		print "</peer-fingerprint>"
+	} > "${srv_inline}-temp"
+	"${EASYTLS_MV}" -f "${srv_inline}-temp" "${srv_inline}"
+
+	# Add node to inline-index
+	TLSKEY_SUBNAME='NOSUBKEY'
+	tlskey_serial=${cv2_Srv_Serial}
+	name="${srv_name}"
+	inline_file="${srv_inline}"
+	inline_index_update add || die "Failed to update inline-index"
+} # => inline_share_fingerprint ()
 
 
 
@@ -4597,8 +4775,6 @@ interactive_build ()
   [2] TLS-Crypt-V1 key               - Basic TLS-crypt-v1 pre-shared key
   [3] TLS-Crypt-V2 key for Server    - Advanced TLS-Crypt-v2 Server key
   [4] TLS-Crypt-V2 key for Client    - Advanced TLS-Crypt-v2 Client key
-  [5] Self-signed server             - Server X509 certificate and key
-  [6] Self-signed client             - Client X509 certificate and key
 
   Select the type of TLS-key to build:'
 	interactive_question
@@ -4813,18 +4989,6 @@ interactive_build ()
 		fi
 
 		return 0
-	;;
-	5)	# Self-signed server
-		cert_type='Server'
-		interactive_selfsign_CN
-		interactive_selfsign_PW
-		build_self_sign "${cert_type}" "${common_name}"
-	;;
-	6)	# Self-signed client
-		cert_type='Client'
-		interactive_selfsign_CN
-		interactive_selfsign_PW
-		build_self_sign "${cert_type}" "${common_name}"
 	;;
 	*)	# Other value -> Quit
 		"$EASYTLS_PRINTF" '\n%s\n' '  Quit!'
@@ -5610,6 +5774,62 @@ interactive_scripts ()
 
 } # => interactive_scripts ()
 
+# Inter-active self-sign menu
+interactive_selfsign ()
+{
+	"$EASYTLS_PRINTF" '\n%s\n' 'Easy-TLS Inter-active self-sign certificate Menu.'
+
+	# Capture the command line to inline
+	cmd_line='inline'
+
+	# Choose Key
+	ia_question_help='
+* Available Self-signed and Inline-file types:'
+	ia_question_text='
+  [1] Self-signed server with TLS-Auth key
+  [2] Self-signed client with TLS-Auth key and shared fingerprints
+  [3] Self-signed server with TLS-Crypt-V1 key
+  [4] Self-signed client with TLS-Crypt-V1 key and shared fingerprints
+  [5] Self-signed server with TLS-Crypt-V2 Server key
+  [6] Self-signed client with TLS-Crypt-V2 Client key and shared fingerprints
+
+  Select the type of self-sign certificate to build:'
+	interactive_question
+
+	case $ia_answer in
+	1)	# Self-signed server with TLS-Auth key
+		cert_type='Server'
+		key_type='tls-auth'
+		[ -f "${EASYTLS_PKI}/tls-auth.key" ] || missing_file "TLS-Auth key"
+		interactive_selfsign_CN
+		svr_name="${common_name}"
+		interactive_selfsign_PW
+		build_self_sign "${cert_type}" "${svr_name}"
+		inline_tls_auth "${svr_name}" 0
+	;;
+	2)	# Self-signed client with TLS-Auth key
+		cert_type='Client'
+		interactive_selfsign_CN
+		cli_name="${common_name}"
+		interactive_selfsign_PW
+		interactive_selfsign_peer
+		EASYTLS_PEER_FPR="${common_name}"
+		build_self_sign "${cert_type}" "${cli_name}"
+		inline_tls_auth "${cli_name}" 1
+		#inline_share_fingerprint "${cli_name}" || die "try again.."
+	;;
+	3|4)
+		[ -f "${EASYTLS_PKI}/tls-crypt.key" ] || missing_file "TLS-crypt key"
+	;;
+	5)
+	;;
+	6)
+	;;
+	*)	# Other value -> Quit
+		"$EASYTLS_PRINTF" '\n%s\n' '  Quit!'
+	esac
+}
+
 # Set commonName and verify this cert does not exist
 interactive_selfsign_CN ()
 {
@@ -5636,7 +5856,34 @@ interactive_selfsign_CN ()
 	done
 }
 
-# Build self-sign cert/key with password
+# Set peer commonName and verify this cert does exist
+interactive_selfsign_peer ()
+{
+	unset common_name
+	ia_question_help='
+* This field only requires the certificate commonName,
+  it does not require the complete file name.'
+
+	while :
+	do
+		ia_question_text="
+  To share your client and server fingerprints,
+  enter the commonName of your * Server * certificate:"
+		interactive_question
+		[ -n "${ia_answer}" ] || continue
+		common_name="${ia_answer}"
+		cert_file="${EASYTLS_PKI}/${common_name}.crt"
+		[ -f "${cert_file}" ] && {
+			cmd_line="${cmd_line} ${common_name}"
+			break
+			}
+		ia_question_text="  Press enter to continue.."
+		printf "\n%s\n\n" "  A certificate named ${common_name} does not exist!"
+		interactive_wait_for_answer
+	done
+}
+
+# Choose self-sign cert/key with/without password
 interactive_selfsign_PW ()
 {
 	unset openssl_nodes
@@ -6775,7 +7022,7 @@ external_deps ()
 	EASYTLS_LS='ls' # NOT Checked by Easy-RSA3
 	EASYTLS_MKDIR='mkdir' # Checked by Easy-RSA3
 	#EASYTLS_MKTEMP='mktemp' # Not used in Easy-TLS
-	#EASYTLS_MV='mv' # Not used in Easy-TLS, NOT Checked by Easy-RSA3
+	EASYTLS_MV='mv' # NOT Checked by Easy-RSA3
 	EASYTLS_PRINTF='printf' # Checked by Easy-RSA3
 	EASYTLS_RM='rm' # Checked by Easy-RSA3
 	EASYTLS_SED='sed'
@@ -6821,7 +7068,11 @@ external_deps ()
 			setup_err=1
 			}
 		[ -f "${EASYTLS_ersabin_dir}/${EASYTLS_LS}.exe" ] || {
-			echo "Missing: ${EASYTLS_ersabin_dir}/${EASYTLS_SED}.exe"
+			echo "Missing: ${EASYTLS_ersabin_dir}/${EASYTLS_LS}.exe"
+			setup_err=1
+			}
+		[ -f "${EASYTLS_ersabin_dir}/${EASYTLS_MV}.exe" ] || {
+			echo "Missing: ${EASYTLS_ersabin_dir}/${EASYTLS_MV}.exe"
 			setup_err=1
 			}
 		[ -f "${EASYTLS_ersabin_dir}/${EASYTLS_SED}.exe" ] || {
@@ -7042,6 +7293,9 @@ main ()
 		-k|--sub-key-name)
 			export TLSKEY_SUBNAME="${val}"
 		;;
+		-r|--ss-peer-fingerprint)
+			export EASYTLS_PEER_FPR="${val}"
+		;;
 		-w|--ss-pass)
 			empty_ok=1
 			export EASYTLS_PASSWORD=1
@@ -7097,7 +7351,6 @@ main ()
 
 	# Die on fatal opt error
 	fatal_opt
-	unset fatal_msg
 
 	# Intelligent env-var detection and auto-loading:
 	vars_setup
@@ -7214,6 +7467,11 @@ main ()
 		script)
 			interactive_scripts || \
 				die "Error: interactive_scripts"
+			cmd='Done'
+		;;
+		ss|selfsign)
+			interactive_selfsign || \
+				die "Error: interactive_selfsign"
 			cmd='Done'
 		;;
 		bta|build-tls-auth)
@@ -7349,15 +7607,15 @@ main ()
 		esac # Everything else
 
 		# EasyTLS auto-check
-		easytls_auto_check || die "Error: easytls_auto_check"
+		easytls_auto_check || die "easytls_auto_check fail"
 
 		# save me!
-		save_wiscii_hash || die "Master hash save failed"
+		save_wiscii_hash || die "save master hash fail"
 	;;
 	esac # help/version/Initialise
 
 } # => main ()
 
-main "$@"
+main "$@" || die "main $*"
 
 # Done
