Re-enable inline_tls_cv2_group_server() and improve comments
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -4167,12 +4167,14 @@ inline_tls_auth ()
 		esac
 	esac
 
-	{	"${EASYTLS_PRINTF}" "%s\n\n" "# TLS auth"
+	{	# Add key
+		"${EASYTLS_PRINTF}" "%s\n\n" "# TLS auth"
 		"${EASYTLS_PRINTF}" "%s\n\n" "key-direction ${key_direction}"
 		"${EASYTLS_PRINTF}" "%s\n" "<tls-auth>"
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-auth>"
 
+		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "inline_tls_auth - inline_share_fingerprint"
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
@@ -4253,13 +4255,16 @@ inline_tls_crypt_v1 ()
 	# Inline base file
 	inline_base "${name}" || die "Failed to create inline base file"
 
-	{	"${EASYTLS_PRINTF}" "%s\n\n" "# TLS crypt"
+	{	# Add key
+		"${EASYTLS_PRINTF}" "%s\n\n" "# TLS crypt"
 		"${EASYTLS_PRINTF}" "%s\n" "<tls-crypt>"
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt>"
 
+		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "inline_tls_crypt_v1 - inline_share_fingerprint"
+
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4451,13 +4456,16 @@ inline_tls_crypt_v2 ()
 			"${EASYTLS_PRINTF}" '\n%s\n' "setenv UV_TLSKEY_SERIAL ${MD_TLSKEY_SERIAL}"
 			"${EASYTLS_PRINTF}" "%s\n\n" "push-peer-info"
 		fi
+
 		# Add key
 		"${EASYTLS_PRINTF}" "%s\n" "<tls-crypt-v2>"
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt-v2>"
+
 		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "inline_tls_crypt_v2 - inline_share_fingerprint"
+
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4492,10 +4500,10 @@ inline_tls_crypt_v2 ()
 inline_tls_cv2_group_server ()
 {
 	# THIS IS CURRENTLY DISABLED
-	print "Only Client keys require the Group setting."
-	print "Use your current standard Server key to build"
-	print "a new server inline file."
-	return 1
+	#print "Only Client keys require the Group setting."
+	#print "Use your current standard Server key to build"
+	#print "a new server inline file."
+	#return 1
 
 	[ "$#" -ge 2 ] || \
 		die "Required option(s): <server_common_name> <server_group_key>"
@@ -4620,13 +4628,16 @@ inline_tls_cv2_group_server ()
 			"${EASYTLS_PRINTF}" '\n%s\n' "setenv UV_TLSKEY_SERIAL ${MD_TLSKEY_SERIAL}"
 			"${EASYTLS_PRINTF}" "%s\n\n" "push-peer-info"
 		fi
+
 		# Add key
 		"${EASYTLS_PRINTF}" "%s\n" "<tls-crypt-v2>"
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt-v2>"
+
 		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "inline_tls_cv2_group_server - inline_share_fingerprint"
+
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4638,6 +4649,7 @@ inline_tls_cv2_group_server ()
 	# Hash inline file and add hash to index
 	save_name="${name}"
 	name="${file_name_stub}"
+	tlskey_serial="${MD_TLSKEY_SERIAL}"
 	if inline_index_update add; then
 		: # OK
 	else
@@ -4653,6 +4665,7 @@ inline_tls_cv2_group_server ()
 	name="${save_name}"
 	unset -v save_name
 
+	# share this client FP with server defined by -r=<serv-name> option
 	inline_share_fingerprint "${name}" || die "Failed to share fingerprint"
 
 	notice "TLS-Crypt-V2 GROUP Server Inline file created: ${inline_file}"
@@ -4818,13 +4831,16 @@ inline_tls_cv2_group_client ()
 			"${EASYTLS_PRINTF}" '\n%s\n' "setenv UV_TLSKEY_SERIAL ${MD_TLSKEY_SERIAL}"
 			"${EASYTLS_PRINTF}" "%s\n\n" "push-peer-info"
 		fi
+
 		# Add key
 		"${EASYTLS_PRINTF}" "%s\n" "<tls-crypt-v2>"
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt-v2>"
+
 		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "inline_tls_cv2_group_client - inline_share_fingerprint"
+
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4852,6 +4868,7 @@ inline_tls_cv2_group_client ()
 	name="${save_name}"
 	unset -v save_name
 
+	# share this client FP with server defined by -r=<serv-name> option
 	inline_share_fingerprint "${name}" || die "Failed to share fingerprint"
 
 	notice "Inline TLS-Crypt-V2 GROUP Client file created: ${inline_file}"
@@ -4865,8 +4882,8 @@ inline_share_fingerprint ()
 	# Normal CA mode ignores this step when building inline files
 	[ -n "${EASYTLS_NO_CA}" ] || return 0
 
+	# Keep count - Note: The first run is always silent
 	isfp_count="$(( isfp_count + 1 ))"
-	easytls_verbose "Run inline_share_fingerprint (${isfp_count})"
 
 	# When first creating this inline add FP <tags> and return
 	if [ "$#" -eq 0 ]; then
@@ -4878,8 +4895,11 @@ inline_share_fingerprint ()
 		return 0
 	fi
 
+	# Verbose message
+	easytls_verbose "Run inline_share_fingerprint (${isfp_count})"
+
 	# If called by a user then require option name
-	[ "$#" -ge 1 ] || die "Required option: client commonName"
+	[ "$#" -gt 0 ] || die "Required option(s): <client_common_name>"
 
 	# Only supported for client - This needs improvement
 	if [ -n "${EASYTLS_PEER_FPR}" ] && {
@@ -6369,13 +6389,18 @@ build_self_sign ()
 		"${EASYTLS_PRINTF}" '%s\n' "<cert>"
 		"${EASYTLS_CAT}" "${cert_file}"
 		"${EASYTLS_PRINTF}" '%s\n\n' "<\cert>"
+
+		# Add key
 		"${EASYTLS_PRINTF}" '%s\n' "<key>"
 		"${EASYTLS_CAT}" "${key_file}"
 		"${EASYTLS_PRINTF}" '%s\n\n' "<\key>"
 
+		# Share fingerprint template
 		inline_share_fingerprint || \
 			die "build_self_sign - inline_share_fingerprint"
 	} > "${inline_file}" || die "Failed to create Inline file for ${cert_name}"
+
+	# share this client FP with server defined by -r=<serv-name> option
 	inline_share_fingerprint "${cert_name}" || \
 		die "inline_share_fingerprint - build_self_sign"
 
