Minor improvements
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -537,7 +537,7 @@ Easy-TLS configurable options (Abbreviation|full option):
      delete an item from config
      Should the need arise, items can now be deleted also.
 "
-} #=> opt_config ()
+} # => opt_config ()
 
 
 
@@ -1316,27 +1316,6 @@ and initialize a fresh TLS PKI here."
 			die "Removal of TLS dir failed. Check/correct errors above"
 	fi
 
-	# Explicitly set EASYTLS_HASH_ALGO here
-	EASYTLS_HASH_ALGO="${EASYTLS_HASH_ALGO:-SHA256}"
-
-	# Set fixed hash
-	case "${EASYTLS_HASH_ALGO}" in
-	SHA1)
-	fixed_hash=1111111111111111111111111111111111111111
-	fixed_length=40
-	;;
-	SHA256)
-	fixed_hash=2222222222222222222222222222222222222222222222222222222222222222
-	fixed_length=64
-	;;
-	*)
-		die "Unknown algorithm: ${EASYTLS_HASH_ALGO}"
-	;;
-	esac
-
-	forbidden_hash="$(openssl_generate_empty_hash)"
-	forbidden_hash="${forbidden_hash%% *}"
-
 	# Create Easy-TLS structure
 	easytls_create_layout || die "init_tls - easytls_create_layout"
 
@@ -1368,7 +1347,9 @@ and initialize a fresh TLS PKI here."
 # Create Easy-TLS data files
 easytls_create_layout ()
 {
+	# Explicitly set EASYTLS_HASH_ALGO here
 	EASYTLS_HASH_ALGO="${EASYTLS_HASH_ALGO:-SHA256}"
+
 	# Set fixed hash
 	case "${EASYTLS_HASH_ALGO}" in
 	SHA1)
@@ -1383,6 +1364,7 @@ easytls_create_layout ()
 		die "Unknown algorithm: ${EASYTLS_HASH_ALGO}"
 	;;
 	esac
+
 	forbidden_hash="$(openssl_generate_empty_hash)"
 	forbidden_hash="${forbidden_hash%% *}"
 
@@ -1543,39 +1525,6 @@ easytls_auto_check ()
 
 	# Update status
 	status_update
-
-	# Check inline-index hash
-	#if [ -z "${inline_index_verify_hash_block}" ]; then
-	#	inline_index_verify_hash || {
-	#		error_msg "inline_index_verify_hash - easytls_auto_check"
-	#		error_msg "* Auto-check: Hash failed for Inline index"
-	#		}
-	#else
-	#	# index has been successfully verified
-	#	:
-	#fi
-
-	# Verify tlskey-index hash
-	#if [ -z "${tlskey_index_verify_hash_block}" ]; then
-	#	tlskey_index_verify_hash || {
-	#		error_msg "tlskey_index_verify_hash - easytls_auto_check"
-	#		error_msg "* Auto-check: Hash failed for TLS key index"
-	#		}
-	#else
-	#	# index has been successfully verified
-	#	:
-	#fi
-
-	# Check disabled-list hash
-	#if [ -z "${disabled_list_verify_hash_block}" ]; then
-	#	disabled_list_verify_hash || {
-	#		error_msg "disabled_list_verify_hash - easytls_auto_check"
-	#		error_msg "* Auto-check: Hash failed for Disabled list"
-	#		}
-	#else
-	#	# index has been successfully verified
-	#	:
-	#fi
 
 	unset -v auto_check
 } # => easytls_auto_check ()
@@ -1985,7 +1934,7 @@ openssl_crt_common_name ()
 		-nameopt sep_multiline -nameopt space_eq -nameopt lname | \
 			"${EASYTLS_GREP}" '^[[:blank:]]*commonName' \
 				|| return 1
-} # => get_openssl_crt_common_name ()
+} # => openssl_crt_common_name ()
 
 # Extract the CommonName from OpenSSL -subject
 get_openssl_crt_common_name ()
@@ -1994,7 +1943,7 @@ get_openssl_crt_common_name ()
 	temp_name="${temp_name#*commonName = }"
 	"${EASYTLS_PRINTF}" '%s' "${temp_name}"
 	unset -v temp_name
-} # => openssl_crt_common_name ()
+} # => get_openssl_crt_common_name ()
 
 
 
@@ -2144,7 +2093,7 @@ noca_status_easytls_output ()
 		else
 		print "  Common-Name " $1 "\t  X509-Serial " $2 "\t  Sub-key " $3
 		}'
-} # => status_easytls_output ()
+} # => noca_status_easytls_output ()
 
 # Format status CN
 status_cn ()
@@ -2241,7 +2190,7 @@ noca_status_x509_valid ()
 		[ -n "${silent_status}" ] || \
 			print "${ersa_valid_cn} ${cert_serial}" | status_easyrsa_output
 	done
-} # => status_easyrsa_valid ()
+} # => noca_status_x509_valid ()
 
 # Print known inline files from Easy-TLS
 noca_status_easytls_inline ()
@@ -2269,7 +2218,7 @@ noca_status_easytls_inline ()
 				| noca_status_easytls_output
 		unset -v etls_valid_name etls_valid_subkey etls_valid_serial
 	done
-} # => status_easytls_inline ()
+} # => noca_status_easytls_inline ()
 
 # Print Revoked certs from Easy-RSA
 status_easyrsa_revoked ()
@@ -2455,7 +2404,7 @@ status_disabled_list ()
 status_update ()
 {
 	if [ -n "${FILE_HASH_DISABLED}" ]; then
-	flash_config=1
+		flash_config=1
 		easytls_config status 1
 	fi
 } # => status_update ()
@@ -3183,7 +3132,6 @@ inline_index_rebuild ()
 	# Temporarily disable
 	warn "inline_index_rebuild is currently disabled."
 	return 0
-
 } # => inline_index_rebuild ()
 
 
@@ -3264,13 +3212,6 @@ tlskey_index_update ()
 			error_msg "tlskey_index_update - del: Failed to delete old record"
 			return 1
 			}
-	;;
-	rehash)
-		# Fall through to save hash
-		:
-			# Disabled - currently..
-			error_msg "tlskey_index_update rehash: Failed."
-			return 1
 	;;
 	*)
 		error_msg "Unknown index action: ${update_index_action}"
@@ -3454,7 +3395,7 @@ verify_group_tlskey_in_use ()
 	x509_patt=".*-${name}[[:blank:]]"
 	tlsk_patt=".*[[:blank:]]${tlskey_serial}"
 	"${EASYTLS_GREP}" "^${x509_patt}${tlsk_patt}\$" "${EASYTLS_INLINE_INDEX}"
-} # => verify_tlskey_in_use ()
+} # => verify_group_tlskey_in_use ()
 
 # Remove a TLS-Crypt-V2 Client key and update the tlskey-index
 remove_tlskey ()
@@ -3555,7 +3496,7 @@ remove_tlskey ()
 
 	notice "TLS-Crypt-V2 key removed: ${tlskey_file}"
 	easytls_verbose
-} # => tlskey_remove ()
+} # => remove_tlskey ()
 
 # Remove a TLS-Crypt-V2 Client key and update the tlskey-index
 remove_group_tlskey ()
@@ -3637,7 +3578,7 @@ remove_group_tlskey ()
 
 	notice "TLS-Crypt-V2 key removed: ${tlskey_file}"
 	easytls_verbose
-} # => tlskey_remove ()
+} # => remove_group_tlskey ()
 
 
 
@@ -3677,6 +3618,7 @@ inline_base ()
 
 	# Not used when called from a function
 	# because functions do not pass any parameters, except name
+	# Do not unset these here because they are set be caller
 	while [ -n "${1}" ]; do
 		case "${1}" in
 			no-key)	no_x509_key=1 ;;
@@ -3868,7 +3810,7 @@ inline_tls_auth ()
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-auth>"
 
-		inline_share_fingerprint
+		inline_share_fingerprint || die "inline_share_fingerprint"
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -3941,7 +3883,7 @@ inline_tls_crypt_v1 ()
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt>"
 
-		inline_share_fingerprint
+		inline_share_fingerprint || die "inline_share_fingerprint"
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4127,7 +4069,7 @@ inline_tls_crypt_v2 ()
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt-v2>"
 		# Share fingerprint template
-		inline_share_fingerprint
+		inline_share_fingerprint || die "inline_share_fingerprint"
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -4470,7 +4412,7 @@ inline_tls_cv2_group_client ()
 		"${EASYTLS_CAT}" "${tlskey_file}"
 		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt-v2>"
 		# Share fingerprint template
-		inline_share_fingerprint
+		inline_share_fingerprint || die "inline_share_fingerprint"
 	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended purpose
@@ -5870,7 +5812,7 @@ build_self_sign ()
 		"${EASYTLS_CAT}" "${key_file}"
 		"${EASYTLS_PRINTF}" '%s\n\n' "<\key>"
 
-		inline_share_fingerprint
+		inline_share_fingerprint || die "inline_share_fingerprint"
 	} > "${inline_file}" || die "Failed to create Inline file for ${cert_name}"
 
 	inline_share_fingerprint "${cert_name}" || \
@@ -5916,7 +5858,7 @@ create_self_sign_cert_pair ()
 
 	# Remove easytls-openssl.cnf and env-var OPENSSL_CNF
 	easytls_openssl_file destroy || \
-		die "Failed to create easytls-openssl.cnf (Permission)"
+		die "Failed to destroy easytls-openssl.cnf (Permission)"
 	update_master_hash=1
 	"${EASYTLS_RM}" -f "${EASYTLS_ECPARAM_TMP}"
 } # => create_self_sign_cert_pair ()
@@ -6130,10 +6072,6 @@ disabled_list_update_and_hash ()
 {
 	# Update time-stamp
 	update_date="${local_date_ascii}"
-	#generate_valid_date_now update_date || {
-	#	error_msg "disabled_list_update_and_hash - generate_valid_date_now"
-	#	return 1
-	#	}
 
 	update_text="# Updated: ${update_date} -- ${action}: ${name}"
 	"${EASYTLS_SED}" -i -e '/^# Updated: .*$/d' "${EASYTLS_DISABLED_LIST}" || {
