OpenSSL 3 compatibility and Quote FINAL variables
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -1205,8 +1205,8 @@ verify_openssl ()
 	openssl_version="${openssl_version%% *}"
 	[ "${#openssl_version}" -gt 3 ] && openssl_version="${openssl_version%.*}"
 	case "${openssl_version}" in
-		3.0|3.1) : ;;
-		1.1) : ;;
+		3.0|3.1) openssl_version=3 ;;
+		1.1) openssl_version=1 ;;
 		*) die "Unsupported OpenSSL version: ${openssl_version}" ;;
 	esac
 } # => verify_openssl ()
@@ -3010,6 +3010,7 @@ remove_metadata ()
 
 	# Actual inline-file hash
 	force_hash=1
+	verified_inline_hash=""
 	generate_and_validate_file_hash "${inline_file}" verified_inline_hash || {
 		error_msg "generate_and_validate_file_hash - remove_metadata"
 		error_msg "${inline_file}"
@@ -3018,7 +3019,7 @@ remove_metadata ()
 	unset -v force_hash
 
 	# Remove client from inline index
-	known_inline_hash=${verified_inline_hash}
+	known_inline_hash="${verified_inline_hash}"
 	inline_serial="$(inline_index_ilhash_to_serial)"
 	inline_index_update del || die "Failed to update inline-index"
 
@@ -5542,6 +5543,8 @@ build_self_sign ()
 	cert_name="${1}"
 	shift # Scrape off name
 
+	verify_openssl || die "build_self_sign -> verify_openssl"
+
 	cert_file="${EASYTLS_PKI}/${cert_name}.crt"
 	key_file="${EASYTLS_PKI}/${cert_name}.key"
 	fpr_file="${EASYTLS_PKI}/${cert_name}.fpr"
@@ -5567,13 +5570,11 @@ build_self_sign ()
 	[sS]erver)
 		# Certificate extension: TLS Web Server
 		EASYTLS_EKU="serverAuth"
-		openssl_eku="-addext extendedKeyUsage"
 		cert_purpose='Server'
 	;;
 	[cC]lient)
 		# Certificate extension: TLS Web Server
 		EASYTLS_EKU="clientAuth"
-		openssl_eku="-addext extendedKeyUsage"
 		cert_purpose='Client'
 	;;
 	*)
@@ -5582,7 +5583,13 @@ build_self_sign ()
 	esac
 
 	# Disable password
-	[ -n "${EASYTLS_PASSWORD}" ] || openssl_nodes="-nodes"
+	if [ -z "${EASYTLS_PASSWORD}" ]; then
+		case "${openssl_version}" in
+		3)	openssl_nopass="-noenc" ;;
+		1)	openssl_nopass="-nodes" ;;
+		*)	die "Unsupport openssl version: ${openssl_version}"
+		esac
+	fi
 
 	# build
 	create_self_sign_cert_pair || \
@@ -5629,14 +5636,22 @@ build_self_sign ()
 # Create an EC key/cert pair
 create_self_sign_cert_pair ()
 {
+	# If ecparams fail then so does req
 	easytls_verbose
 	"${EASYRSA_OPENSSL}" ecparam -name "${EASYTLS_EC_CURVE}" \
 		> "${EASYTLS_ECPARAM_TMP}"
-	# If ecparams fail then so does req
-	"${EASYRSA_OPENSSL}" req -x509 -newkey ec:"${EASYTLS_ECPARAM_TMP}" \
-		${openssl_nodes} -sha256 -days="${EASYTLS_SS_AGE}" -text -utf8 \
-		-keyout "${key_file}" -out "${cert_file}" -subj "/CN=${cert_name}" \
-		${openssl_eku}=${EASYTLS_EKU} || return 1
+	# Separate commands for utterly stupid -nodes/-noenc not set error
+	if [ -z "${EASYTLS_PASSWORD}" ]; then
+		"${EASYRSA_OPENSSL}" req -x509 -newkey ec:"${EASYTLS_ECPARAM_TMP}" \
+			"${openssl_nopass}" -sha256 -days="${EASYTLS_SS_AGE}" -text -utf8 \
+			-keyout "${key_file}" -out "${cert_file}" -subj "/CN=${cert_name}" \
+			-addext extendedKeyUsage="${EASYTLS_EKU}" || return 1
+	else
+		"${EASYRSA_OPENSSL}" req -x509 -newkey ec:"${EASYTLS_ECPARAM_TMP}" \
+			-sha256 -days="${EASYTLS_SS_AGE}" -text -utf8 \
+			-keyout "${key_file}" -out "${cert_file}" -subj "/CN=${cert_name}" \
+			-addext extendedKeyUsage="${EASYTLS_EKU}" || return 1
+	fi
 
 	update_master_hash=1
 	"${EASYTLS_RM}" -f "${EASYTLS_ECPARAM_TMP}"
@@ -6074,7 +6089,7 @@ interactive_build ()
 
 			# Create inline
 			inline_tls_crypt_v2 "$opt_server_name" \
-				${opt_no_key} ${opt_add_dh} ${opt_custom_dh} || {
+				"${opt_no_key}" "${opt_add_dh}" "${opt_custom_dh}" || {
 					error_msg '**Create inline-file failed'
 					return 1
 					}
@@ -6145,8 +6160,8 @@ interactive_build ()
 		require_batch=1
 
 		# Build key
-		${easytls_cmd} "$opt_server_name" "$opt_client_name" \
-			${opt_hardware} || {
+		"${easytls_cmd}" "$opt_server_name" "$opt_client_name" \
+			"${opt_hardware}" || {
 				error_msg '**Build TLS-CryptV2 Client key failed'
 				return 1
 				}
@@ -6212,7 +6227,7 @@ interactive_build ()
 
 			# Create inline
 			"${easytls_cmd}" "$opt_client_name" "$opt_gkey_name" \
-				${opt_no_key} ${opt_no_md} ${opt_add_hw} || {
+				"${opt_no_key}" "${opt_no_md}" "${opt_add_hw}" || {
 					error_msg '**Create inline-file failed'
 					return 1
 					}
@@ -6286,8 +6301,8 @@ interactive_inline ()
 		interactive_show_cmd
 
 		# Build .inline
-		inline_tls_auth "${opt_common_name}" \
-			${key_direction} ${opt_no_key} ${opt_add_dh} ${opt_custom_dh} || {
+		inline_tls_auth "${opt_common_name}" "${key_direction}" \
+			"${opt_no_key}" "${opt_add_dh}" "${opt_custom_dh}" || {
 				error_msg '**Create inline-file failed'
 				return 1
 				}
@@ -6327,7 +6342,7 @@ interactive_inline ()
 
 		# Build .inline
 		inline_tls_crypt_v1 "${opt_common_name}" \
-			${opt_no_key} ${opt_add_dh} ${opt_custom_dh} || {
+			"${opt_no_key}" "${opt_add_dh}" "${opt_custom_dh}" || {
 				error_msg '**Create inline-file failed'
 				return 1
 				}
@@ -6361,7 +6376,7 @@ interactive_inline ()
 
 		# Build .inline
 		inline_tls_crypt_v2 "${opt_common_name}" \
-			${opt_no_key} ${opt_add_dh} || {
+			"${opt_no_key}" "${opt_add_dh}" || {
 				error_msg '**Create inline-file failed'
 				return 1
 				}
@@ -6421,8 +6436,8 @@ interactive_inline ()
 		interactive_show_cmd
 
 		# Build .inline
-		${easytls_cmd} "${opt_common_name}" "${opt_gkey_name}" \
-			${opt_no_key} ${opt_no_md} ${opt_add_hw} || {
+		"${easytls_cmd}" "${opt_common_name}" "${opt_gkey_name}" \
+			"${opt_no_key}" "${opt_no_md}" "${opt_add_hw}" || {
 				error_msg '**Create inline-file failed'
 				return 1
 				}
@@ -6805,7 +6820,7 @@ interactive_remove ()
 		require_batch=1
 
 		# Remove .inline
-		remove_metadata "$opt_name" ${opt_pattern} || {
+		remove_metadata "$opt_name" "${opt_pattern}" || {
 			error_msg '**Remove metadata failed'
 			return 1
 			}
