Use more {} for variable names and very minor corrections
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -1071,13 +1071,13 @@ config_version ()
 verify_openvpn ()
 {
 	# extract openvpn version
-	openvpn_full_version="$("$EASYTLS_OPENVPN" --version)"
+	openvpn_full_version="$("${EASYTLS_OPENVPN}" --version)"
 	openvpn_version="${openvpn_full_version%% *}"
-	case "$openvpn_version" in
+	case "${openvpn_version}" in
 		OpenVPN) : ;;
 		*)
 			help_note="See ./easytls help options - Option: --openvpn"
-			die "Missing or invalid OpenVPN: $openvpn_version"
+			die "Missing or invalid OpenVPN: ${openvpn_version}"
 		;;
 	esac
 
@@ -1085,10 +1085,10 @@ verify_openvpn ()
 	openvpn_version="${openvpn_version%% *}"
 	openvpn_version="${openvpn_version%_*}"
 	[ ${#openvpn_version} -gt 3 ] && openvpn_version="${openvpn_version%.*}"
-	case "$openvpn_version" in
+	case "${openvpn_version}" in
 		2.5|2.6) : ;;
 		2.4) : ;;
-		*) die "Unsupported OpenVPN version: $openvpn_version" ;;
+		*) die "Unsupported OpenVPN version: ${openvpn_version}" ;;
 	esac
 } # => verify_openvpn ()
 
@@ -1096,14 +1096,16 @@ verify_openvpn ()
 verify_tls_init ()
 {
 	{
-		[ -d "$EASYTLS_PKI" ] && \
-		[ -f "$EASYTLS_CONFIG_FILE" ] && \
-		[ -f "$EASYTLS_INLINE_INDEX" ] && \
-		[ -f "$EASYTLS_INLINE_X_HASH" ] && \
-		[ -f "$EASYTLS_KEY_INDEX" ] && \
-		[ -f "$EASYTLS_KEY_X_HASH" ] && \
-		[ -f "$EASYTLS_DISABLED_LIST" ] && \
-		[ -f "$EASYTLS_DISABLED_HASH" ]
+		[ -d "${EASYTLS_PKI}" ] && \
+		[ -f "${EASYTLS_WISCII_HASH}" ] && \
+		[ -f "${EASYTLS_CONFIG_FILE}" ] && \
+		[ -f "${EASYTLS_CONFIG_HASH}" ] && \
+		[ -f "${EASYTLS_INLINE_INDEX}" ] && \
+		[ -f "${EASYTLS_INLINE_X_HASH}" ] && \
+		[ -f "${EASYTLS_KEY_INDEX}" ] && \
+		[ -f "${EASYTLS_KEY_X_HASH}" ] && \
+		[ -f "${EASYTLS_DISABLED_LIST}" ] && \
+		[ -f "${EASYTLS_DISABLED_HASH}" ]
 	} || return 1
 } # => verify_tls_init ()
 
@@ -1115,20 +1117,20 @@ init_tls ()
 
 	# If EASYTLS_PKI exists, confirm before we remove
 	# skipped with EASYTLS_BATCH
-	if [ -d "$EASYTLS_PKI" ]; then
+	if [ -d "${EASYTLS_PKI}" ]; then
 		confirm "Confirm removal: " "yes" "
 WARNING!!!
 
 You are about to remove the EASYTLS_PKI at: $EASYTLS_PKI
 and initialize a fresh TLS PKI here."
 		# now remove it:
-		"$EASYTLS_RM" -rf "$EASYTLS_PKI" \
+		"${EASYTLS_RM}" -rf "${EASYTLS_PKI}" \
 		|| die "Removal of TLS dir failed. Check/correct errors above"
 	fi
 
-	while [ -n "$1" ]; do
-		case "$1" in
-			sha1|SHA1) EASYTLS_HASH_ALGO="$1" ;;
+	while [ -n "${1}" ]; do
+		case "${1}" in
+			sha1|SHA1) EASYTLS_HASH_ALGO="${1}" ;;
 			nc|no-ca) EASYTLS_NO_CA=1 ;;
 			*) warn "Ignoring unknown command option: '$1'" ;;
 		esac
@@ -1139,27 +1141,30 @@ and initialize a fresh TLS PKI here."
 	EASYTLS_HASH_ALGO="${EASYTLS_HASH_ALGO:-SHA256}"
 
 	# Create easytls dir in EasyRSA-PKI dir
-	"$EASYTLS_MKDIR" -p "$EASYTLS_PKI" || die "Failed to create easytls dir"
+	"${EASYTLS_MKDIR}" -p "${EASYTLS_PKI}" || \
+		die "Failed to create easytls dir"
 
 	# Create data dir in easytls dir
-	"$EASYTLS_MKDIR" -p "$EASYTLS_DATA_DIR" || die "Failed to create data dir"
+	"${EASYTLS_MKDIR}" -p "${EASYTLS_DATA_DIR}" || \
+		die "Failed to create data dir"
 
 	# Create metadata dir in easytls dir
-	"$EASYTLS_MKDIR" -p "$EASYTLS_MD_DIR" || die "Failed to create metadata dir"
+	"${EASYTLS_MKDIR}" -p "${EASYTLS_MD_DIR}" || \
+		die "Failed to create metadata dir"
 
 	# Create config-file
 	{
-		"$EASYTLS_PRINTF" '%s\n' "no.ca = ${EASYTLS_NO_CA}"
-		"$EASYTLS_PRINTF" '%s\n' "hash.algorithm = ${EASYTLS_HASH_ALGO}"
-		"$EASYTLS_PRINTF" '%s\n' "tmp.dir = "
-		"$EASYTLS_PRINTF" '%s\n' "ca.id = "
-		"$EASYTLS_PRINTF" '%s\n' "custom.group = "
-		"$EASYTLS_PRINTF" '%s\n' "auto.check = on"
-		"$EASYTLS_PRINTF" '%s\n' "inline.metadata = on"
-		"$EASYTLS_PRINTF" '%s\n' "inline.hardware = off"
-		"$EASYTLS_PRINTF" '%s\n' "custom.openvpn = "
-		"$EASYTLS_PRINTF" '%s\n' "status = 0"
-	} > "$EASYTLS_CONFIG_FILE" || die "Failed to create config-file"
+		"${EASYTLS_PRINTF}" '%s\n' "no.ca = ${EASYTLS_NO_CA}"
+		"${EASYTLS_PRINTF}" '%s\n' "hash.algorithm = ${EASYTLS_HASH_ALGO}"
+		"${EASYTLS_PRINTF}" '%s\n' "tmp.dir = "
+		"${EASYTLS_PRINTF}" '%s\n' "ca.id = "
+		"${EASYTLS_PRINTF}" '%s\n' "custom.group = "
+		"${EASYTLS_PRINTF}" '%s\n' "auto.check = on"
+		"${EASYTLS_PRINTF}" '%s\n' "inline.metadata = on"
+		"${EASYTLS_PRINTF}" '%s\n' "inline.hardware = off"
+		"${EASYTLS_PRINTF}" '%s\n' "custom.openvpn = "
+		"${EASYTLS_PRINTF}" '%s\n' "status = 0"
+	} > "${EASYTLS_CONFIG_FILE}" || die "Failed to create config-file"
 
 	# Set fixed hash
 	case ${EASYTLS_HASH_ALGO} in
@@ -1182,26 +1187,26 @@ and initialize a fresh TLS PKI here."
 	config_save_hash || die "Failed to hash config-file"
 
 	# Create inline-index
-	head_text="# EasyTLS inline-index - Created: $(date)"
-	head_text="$head_text - inline-hash|inline-serial|CN|sub-key|tlskey-serial"
-	"$EASYTLS_PRINTF" '%s\n' "$head_text" > "$EASYTLS_INLINE_INDEX" || \
+	head_text="# EasyTLS inline-index - Created: $("${EASYTLS_DATE}")"
+	head_text="${head_text} - inline-hash|inline-serial|CN|sub-key|tlskey-serial"
+	"${EASYTLS_PRINTF}" '%s\n' "${head_text}" > "${EASYTLS_INLINE_INDEX}" || \
 		die "Failed to create inline-index"
 
 	# Save inline-index hash
 	inline_index_save_hash || die "Failed to hash inline-index"
 
 	# Create tlskey-index
-	head_text="# EasyTLS tlskey-index - Created: $(date)"
-	head_text="$head_text - tlskey-serial|cert-serial|CN|sub-key"
-	"$EASYTLS_PRINTF" '%s\n' "$head_text" > "$EASYTLS_KEY_INDEX" || \
+	head_text="# EasyTLS tlskey-index - Created: $("${EASYTLS_DATE}")"
+	head_text="${head_text} - tlskey-serial|cert-serial|CN|sub-key"
+	"${EASYTLS_PRINTF}" '%s\n' "${head_text}" > "${EASYTLS_KEY_INDEX}" || \
 		die "Failed to create tlskey-index"
 
 	# Save tlskey-index hash
 	tlskey_index_save_hash || die "Failed to create tlskey-index Hash."
 
 	# Create disabled-list
-	head_text="# EastTLS disabled-list - Created: $(date)"
-	"$EASYTLS_PRINTF" '%s\n' "$head_text" > "$EASYTLS_DISABLED_LIST" || \
+	head_text="# EastTLS disabled-list - Created: $("${EASYTLS_DATE}")"
+	"${EASYTLS_PRINTF}" '%s\n' "${head_text}" > "${EASYTLS_DISABLED_LIST}" || \
 		die "Failed to create disabled-list"
 
 	# Save disabled-list hash
@@ -1210,24 +1215,22 @@ and initialize a fresh TLS PKI here."
 	# Auto-save the current EasyRSA CA-ID if available, warn if not
 	if [ $EASYTLS_NO_CA ]
 	then
-		# create issued
-		#"${EASYTLS_MKDIR}" -p "${EASYRSA_PKI}/issued"
 		# Ignore
 		:
 	else
 		EASYTLS_INIT=1
-		save_id || "$EASYTLS_PRINTF" '%s\n\n' "      Failed to Save CA-ID."
+		save_id || "${EASYTLS_PRINTF}" '%s\n\n' "      Failed to Save CA-ID."
 		unset EASYTLS_INIT
 	fi
 
 	# Create empty master hash
-	"$EASYTLS_PRINTF" '%s' "" > "$EASYTLS_WISCII_HASH" || \
+	"${EASYTLS_PRINTF}" '%s' "" > "${EASYTLS_WISCII_HASH}" || \
 		die "Create master-hash failed"
 
 	notice "init-tls complete; you may now create TLS keys and .inline files.
   Your newly created TLS dir is:
 
-    $EASYTLS_PKI"
+    ${EASYTLS_PKI}"
 
 	notice "To configure your Easy-TLS custom group now, use:
     'easytls config custom.group YOUR_GROUP'"
@@ -1253,7 +1256,6 @@ and initialize a fresh TLS PKI here."
 # Run on exit to avoid "chicken and egg" with init-tls
 easytls_auto_check ()
 {
-	#[ $EASYTLS_REMOTE_CI ] && return 0
 	[ $status_disabled_auto_check ] && return 0
 	[ $auto_check_disabled ] && easytls_verbose "auto-check disabled" && return 0
 
@@ -2322,7 +2324,7 @@ inline_index_rebuild ()
 	etls_inline_CNsub_name_list="$(inline_index_common_name_sub_name_list)"
 
 	# Create tls dir index file
-	head_text="# EastTLS inline-index - Created: $(date)"
+	head_text="# EastTLS inline-index - Created: $("${EASYTLS_DATE}")"
 	"$EASYTLS_PRINTF" '%s\n' "$head_text" > "$EASYTLS_INLINE_INDEX" || \
 		inline_index_rebuild_reset "Failed to create inline-index"
 
@@ -4022,7 +4024,7 @@ disabled_list_manager ()
 disabled_list_update_and_hash ()
 {
 	# Update time-stamp
-	update_text="# Updated: $(date) -- ${action}: ${name}"
+	update_text="# Updated: $("${EASYTLS_DATE}") -- ${action}: ${name}"
 	"${EASYTLS_SED}" -i -e '/^# Updated: .*$/d' "${EASYTLS_DISABLED_LIST}" || {
 		error_msg "disabled_list_update_and_hash - sed failed"
 		return 1
