Improve/simplify Fatal error: Missing *expected* "$val" to "$opt"
Fatal errors should be precisely coded, not "obfuscated".

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -9300,7 +9300,14 @@ main () {
 		# Separate option from value:
 		opt="${1%%=*}"
 		val="${1#*=}"
-		empty_ok="" # Empty values are not allowed unless excepted
+
+		# Empty values are not allowed unless expected
+		unset -v is_empty empty_ok
+		# eg: '--batch'
+		[ "$opt" = "$val" ] && is_empty=1
+		# eg: '--pki-dir='
+		[ "$val" ] || is_empty=1
+
 
 		case "${opt}" in
 
@@ -9385,10 +9392,10 @@ main () {
 		esac
 
 		# fatal error when no value was provided
-		if [ -z "${empty_ok}" ] && { [ "${val}" = "${1}" ] || [ -z "${val}" ]; }
-		then
-			fatal_opt "Missing value to option: ${opt}"
+		if [ "$is_empty" ]; then
+			[ "$empty_ok" ] || die "Missing value to option: $opt"
 		fi
+
 		shift
 	done
 
