Introduce inter-active script for easytls-cryptv2-client-connect.sh
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -3768,9 +3768,31 @@ To cancel this inter-active menu at any time, press Control-C
 		print '
   Coming soon ..'
 
-		# -t|--tmp-dir=<path>
-		# -r|--required
+		# -t|--tmp-dir - opt_tmp_dir
+		interactive_tmp_dir
 
+		# -r|--required
+		interactive_hw_required
+
+		# Create config
+		#interactive_create_verify_config
+
+		{	printf '%s\n' '# Configure OpenVPN to use easytls-cryptv2-client-connect.sh'
+			printf '%s\n' '# Add this line to your OpenVPN Server config file'
+			printf '%s' 'client-connect'
+			printf ' %s' "$EASYTLS_CLICON_SH"
+			[ $opt_tmp_dir ] && printf ' %s' "$opt_tmp_dir"
+			[ $opt_hw_required ] && printf ' %s' "$opt_hw_required"
+			printf '\n'
+		} > "$EASYTLS_CLICON_CFG" || die "Failed to create config file"
+
+		# Show config
+		printf '\n'
+		cat "$EASYTLS_CLICON_CFG"
+		printf '\n'
+
+		easytls_verbose
+		easytls_verbose "wotsa config ?"
 	;;
 	*)	# Other value -> Quit
 		print "Quit!"
@@ -4243,6 +4265,33 @@ interactive_x509_method ()
 	[ $opt_preload_id ] && easytls_verbose "Config: $opt_preload_id"
 } # => interactive_x509_method ()
 
+# Set use of hardware-address required
+interactive_hw_required ()
+{
+	unset opt_hw_required
+	default='Y'
+	EASYTLS_QHELP='
+* Do you want to use the hardware-address required flag ? (Default is Yes)'
+	EASYTLS_QTEXT='
+  Enter (y)es or (n)o:'
+	while :
+	do
+		interactive_question
+		EASYTLS_ANSWER="${EASYTLS_ANSWER:-$default}"
+		case "$EASYTLS_ANSWER" in
+			Y|y|Yes|yes|YES)
+				opt_hw_required='-r'
+				break
+			;;
+			N|n|No|no|NO)
+				break
+			;;
+		esac
+	done
+
+	easytls_verbose
+	easytls_verbose "Config: $opt_hw_required"
+}
 
 
 ############################################################################
