Disable verifying hashes which have been verified via master hash
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -1517,37 +1517,37 @@ easytls_auto_check ()
 		warn "EasyTLS: Invalid .inline files found: Renewed certs."
 
 	# Check inline-index hash
-	if [ -z "${inline_index_verify_hash_block}" ]; then
-		inline_index_verify_hash || {
-			error_msg "inline_index_verify_hash - easytls_auto_check"
-			error_msg "* Auto-check: Hash failed for Inline index"
-			}
-	else
-		# index has been successfully verified
-		:
-	fi
+	#if [ -z "${inline_index_verify_hash_block}" ]; then
+	#	inline_index_verify_hash || {
+	#		error_msg "inline_index_verify_hash - easytls_auto_check"
+	#		error_msg "* Auto-check: Hash failed for Inline index"
+	#		}
+	#else
+	#	# index has been successfully verified
+	#	:
+	#fi
 
 	# Verify tlskey-index hash
-	if [ -z "${tlskey_index_verify_hash_block}" ]; then
-		tlskey_index_verify_hash || {
-			error_msg "tlskey_index_verify_hash - easytls_auto_check"
-			error_msg "* Auto-check: Hash failed for TLS key index"
-			}
-	else
-		# index has been successfully verified
-		:
-	fi
+	#if [ -z "${tlskey_index_verify_hash_block}" ]; then
+	#	tlskey_index_verify_hash || {
+	#		error_msg "tlskey_index_verify_hash - easytls_auto_check"
+	#		error_msg "* Auto-check: Hash failed for TLS key index"
+	#		}
+	#else
+	#	# index has been successfully verified
+	#	:
+	#fi
 
 	# Check disabled-list hash
-	if [ -z "${disabled_list_verify_hash_block}" ]; then
-		disabled_list_verify_hash || {
-			error_msg "disabled_list_verify_hash - easytls_auto_check"
-			error_msg "* Auto-check: Hash failed for Disabled list"
-			}
-	else
-		# index has been successfully verified
-		:
-	fi
+	#if [ -z "${disabled_list_verify_hash_block}" ]; then
+	#	disabled_list_verify_hash || {
+	#		error_msg "disabled_list_verify_hash - easytls_auto_check"
+	#		error_msg "* Auto-check: Hash failed for Disabled list"
+	#		}
+	#else
+	#	# index has been successfully verified
+	#	:
+	#fi
 
 	unset -v auto_check
 } # => easytls_auto_check ()
@@ -2686,10 +2686,7 @@ inline_index_update ()
 	update_index_action="${1}"
 
 	# Verify inline-index Hash
-	inline_index_verify_hash || {
-		error_msg "inline-index is corrupt"
-		return 1
-		}
+	#inline_index_verify_hash || { error_msg "inline-index is corrupt"; return 1; }
 
 	if [ "${update_index_action}" = 'del' ] && [ -n "${force_remove}" ]; then
 		update_index_action='force-del'
@@ -3263,7 +3260,7 @@ tlskey_index_update ()
 
 	# Verify tlskey_serial and tlskey-index Hash
 	[ -n "${tlskey_serial}" ] || return 1
-	tlskey_index_verify_hash || return 1
+	#tlskey_index_verify_hash || { error_msg "tlskey-index is corrupt"; return 1; }
 
 	# Update
 	case "${update_index_action}" in
@@ -3354,12 +3351,15 @@ tlskey_index_update ()
 # Verify current tlskey-index hash
 tlskey_index_verify_hash ()
 {
+	[ -z "${tlskey_index_verify_hash_block}" ] || \
+		die "tlskey index verify hash must only run once"
 	generate_and_match_valid_hash \
 		"${EASYTLS_KEY_INDEX}" "${EASYTLS_KEY_X_HASH}" || {
 			error_msg "generate_and_match_valid_hash - tlskey_index_verify_hash"
 			return 1
 			}
 	easytls_verbose "tlskey-index hash check OK"
+	tlskey_index_verify_hash_block=1
 } # => tlskey_index_verify_hash ()
 
 # Save tlskey-index hash
@@ -6047,7 +6047,7 @@ disabled_list_manager ()
 	confirm  "${action} tlskey file ? " "yes" "${action}: ${tlskey_file}"
 
 	# Verify disabled-list Hash
-	disabled_list_verify_hash || die "Disabled list is corrupt."
+	#disabled_list_verify_hash || die "Disabled list is corrupt."
 
 	# Check disabled-list for this tlskey-serial
 	if "${EASYTLS_GREP}" -q "^${tlskey_serial}[[:blank:]]" \
@@ -6187,12 +6187,15 @@ disabled_list_update_and_hash ()
 # Verify current disable-list hash
 disabled_list_verify_hash ()
 {
+	[ -z "${disabled_list_verify_hash_block}" ] || \
+		die "tlskey index verify hash must only run once"
 	generate_and_match_valid_hash \
 		"${EASYTLS_DISABLED_LIST}" "${EASYTLS_DISABLED_HASH}" || {
 			error_msg "disabled_list_verify_hash - fail"
 			return 1
 			}
 	easytls_verbose "Disabled-list hash check OK"
+	disabled_list_verify_hash_block=1
 } # => disabled_list_verify_hash ()
 
 # Save new disable-list hash
@@ -8770,7 +8773,8 @@ generate_master_list ()
 	[ -z "${FILE_HASH_DISABLED}" ] || return 0
 
 	# Initialise inline-list to the inline index file
-	inline_file_list="${EASYTLS_INLINE_INDEX}"
+	inline_file_list="${EASYTLS_INLINE_INDEX}
+${EASYTLS_INLINE_X_HASH}"
 
 	# Hash all inline-files
 	# shellcheck disable=SC2034 # Appear unused
@@ -8800,7 +8804,8 @@ ${inline_file}"
 		saved_inline_hash inline_serial_UNUSED CN sub_key tlskey_serial_UNUSED
 
 	# Initialise tlskey-list to the tlskey index file
-	tlskey_file_list="${EASYTLS_KEY_INDEX}"
+	tlskey_file_list="${EASYTLS_KEY_INDEX}
+${EASYTLS_KEY_X_HASH}"
 
 	# Hash all tlskey_file
 	# tls-auth / tls-crypt
@@ -8840,8 +8845,9 @@ ${tlskey_file}"
 
 	# Add config-file and disabled-list to the UTIL list
 	util_file_list="${EASYTLS_CONFIG_FILE}
-${EASYTLS_DISABLED_LIST}"
-
+${EASYTLS_CONFIG_HASH}
+${EASYTLS_DISABLED_LIST}
+${EASYTLS_DISABLED_HASH}"
 } # => generate_master_list ()
 
 # Master hash
