Replace 'grep' with "$EASYTLS_GREP"
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -669,7 +669,7 @@ easytls_config ()
 config_update ()
 {
 	# Find the pattern
-	grep -q "^${cfg_opt}[[:blank:]]=[[:blank:]].*$" "$EASYTLS_CONFIG_FILE" || {
+	"$EASYTLS_GREP" -q "^${cfg_opt}[[:blank:]]=[[:blank:]].*$" "$EASYTLS_CONFIG_FILE" || {
 		error_msg "config_update - input error"
 		return 1
 		}
@@ -975,7 +975,7 @@ easytls_auto_check ()
 
 	# If inline-index does not exist then do not auto-check
 	[ -f "$EASYTLS_INLINE_INDEX" ] || return 0
-	index_size="$(grep -c '^.*$' "$EASYTLS_INLINE_INDEX")"
+	index_size="$("$EASYTLS_GREP" -c '^.*$' "$EASYTLS_INLINE_INDEX")"
 	[ $index_size -gt 50 ] && \
 		warn "EasyTLS: 50+ .inline files found, use --disable-auto-check"
 
@@ -1028,11 +1028,11 @@ generate_file_hash ()
 	generated_hash="${openssl_hash%% *}"
 
 	# Test it
-	printf '%s' "$generated_hash" | grep -q '[[:blank:][:punct:]]' && {
+	printf '%s' "$generated_hash" | "$EASYTLS_GREP" -q '[[:blank:][:punct:]]' && {
 		error_msg "generate_file_hash - Invalid hash: $generated_hash"
 		return 1
 		}
-	printf '%s' "$generated_hash" | grep -q '^[[:xdigit:]]\+$' || {
+	printf '%s' "$generated_hash" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || {
 		error_msg "generate_file_hash - Invalid hash: $generated_hash"
 		return 1
 		}
@@ -1195,27 +1195,27 @@ status_cn ()
 # Extract Valid records from OpenSSL index.txt by crt_serial
 status_valid_extract_cn ()
 {
-	grep "^V.*[[:blank:]]${i}[[:blank:]]" "$EASYRSA_INDEX" | status_cn
+	"$EASYTLS_GREP" "^V.*[[:blank:]]${i}[[:blank:]]" "$EASYRSA_INDEX" | status_cn
 }
 
 # Extract Revoked records from OpenSSL index.txt by crt_serial
 status_revoked_extract_cn ()
 {
-	grep "^R.*[[:blank:]]${i}[[:blank:]]" "$EASYRSA_INDEX" | status_cn
+	"$EASYTLS_GREP" "^R.*[[:blank:]]${i}[[:blank:]]" "$EASYRSA_INDEX" | status_cn
 }
 
 # Search ersa revoked serial list for etls valid serial
 status_search_revoked_serial_list()
 {
 	printf '%s\n' "$ersa_revoked_serial_list" | \
-		grep -c "^${inline_serial}$"
+		"$EASYTLS_GREP" -c "^${inline_serial}$"
 }
 
 # List the invalid inline file record by serial number
 # Do not terminate regex with $ because we need to allow for subs
 status_invalid_inline_list ()
 {
-	grep "^${verified_inline_hash}[[:blank:]]${inline_serial}[[:blank:]]" \
+	"$EASYTLS_GREP" "^${verified_inline_hash}[[:blank:]]${inline_serial}[[:blank:]]" \
 		"$EASYTLS_INLINE_INDEX" | status_easytls_output
 }
 
@@ -1223,7 +1223,7 @@ status_invalid_inline_list ()
 status_easyrsa_valid ()
 {
 	[ -f "$EASYRSA_INDEX" ] || return 0
-	ersa_valid_serial_list="$(grep '^V' "$EASYRSA_INDEX"|"$EASYTLS_AWK" '{print $3}')"
+	ersa_valid_serial_list="$("$EASYTLS_GREP" '^V' "$EASYRSA_INDEX"|"$EASYTLS_AWK" '{print $3}')"
 	for i in $ersa_valid_serial_list
 	do
 		ersa_valid_cn="$(status_valid_extract_cn)"
@@ -1236,7 +1236,7 @@ status_easyrsa_valid ()
 status_easyrsa_revoked ()
 {
 	[ -f "$EASYRSA_INDEX" ] || return 0
-	ersa_revoked_serial_list="$(grep '^R' "$EASYRSA_INDEX" | "$EASYTLS_AWK" '{print $4}')"
+	ersa_revoked_serial_list="$("$EASYTLS_GREP" '^R' "$EASYRSA_INDEX" | "$EASYTLS_AWK" '{print $4}')"
 	for i in $ersa_revoked_serial_list
 	do
 		ersa_revoked_cn="$(status_revoked_extract_cn)"
@@ -1428,11 +1428,11 @@ status_disabled_list()
 # Verify certificate purpose
 verify_cert_purpose ()
 {
-	"$EASYRSA_OPENSSL" x509 -in "$1" -noout -purpose | grep -q "$2"
+	"$EASYRSA_OPENSSL" x509 -in "$1" -noout -purpose | "$EASYTLS_GREP" -q "$2"
 
 	#Purpose="${2#?}"
 	#"$EASYRSA_OPENSSL" x509 -in "$1" -noout -purpose | \
-	#	grep -q "SSL .${Purpose} : Yes"
+	#	"$EASYTLS_GREP" -q "SSL .${Purpose} : Yes"
 } # => verify_cert_purpose ()
 
 # Cut to only certificate enddate
@@ -1445,7 +1445,7 @@ crt_expire_date ()
 # Extract enddate from .inline certificate
 inline_expire_date ()
 {
-	inline_expire="$(grep '^[[:blank:]]\+Not After : ' "$inline_file")"
+	inline_expire="$("$EASYTLS_GREP" '^[[:blank:]]\+Not After : ' "$inline_file")"
 	inline_expire="${inline_expire##*: }"
 } # => inline_expire_date ()
 
@@ -1495,7 +1495,7 @@ cert_expire ()
 		crt_expire_date
 		print " Certificate: $name.crt   Expire-date: $crt_expire"
 	else
-		easyrsa_valid_list="$(grep '^V' "$EASYRSA_INDEX"|status_cn)"
+		easyrsa_valid_list="$("$EASYTLS_GREP" '^V' "$EASYRSA_INDEX"|status_cn)"
 		for name in $easyrsa_valid_list
 		do
 			crt_file="$EASYRSA_PKI/issued/$name.crt"
@@ -1590,7 +1590,7 @@ inline_index_update ()
 		old_record="${verified_inline_hash}[[:blank:]]${inline_serial}[[:blank:]]"
 
 		# Find old record
-		grep -q "^${old_record}" "$EASYTLS_INLINE_INDEX" || {
+		"$EASYTLS_GREP" -q "^${old_record}" "$EASYTLS_INLINE_INDEX" || {
 			error_msg "inline_index_update del: Failed to find: $old_record"
 			return 1
 			}
@@ -1758,7 +1758,7 @@ verify_inline_hash ()
 	# Maybe close this as "EasyRSA leaves an indeterminate grace period for
 	# partially renewed certs to be completely renewed by revoking the old cert"
 	# EasyTLS can work with that
-	#grep "^${name}[[:blank:]].*$" \
+	#"$EASYTLS_GREP" "^${name}[[:blank:]].*$" \
 	#	"$EASYTLS_INLINE_INDEX" | "$EASYTLS_AWK" '{print $2}'
 
 	#script="{if(\$1 ~ /^${name}\$/) print \$2}"
@@ -1804,7 +1804,7 @@ inline_index_search_inline_hash ()
 {
 	# Do not need to search for --sub-key-name
 	# because inline file HASH ${real_hash} is unique
-	grep -q "^${real_hash}[[:blank:]]${inline_serial}[[:blank:]]" \
+	"$EASYTLS_GREP" -q "^${real_hash}[[:blank:]]${inline_serial}[[:blank:]]" \
 		"$EASYTLS_INLINE_INDEX"
 }
 
@@ -1812,27 +1812,27 @@ inline_index_search_inline_hash ()
 #inline_index_search_valid_cn_list ()
 #{
 #	printf '%s\n' "$etls_inline_record_list" | \
-#		grep -c "[[:blank:]]${name}[[:blank:]]"
+#		"$EASYTLS_GREP" -c "[[:blank:]]${name}[[:blank:]]"
 #}
 
 # Dragon be here ! - Extract CN from OpenSSL index.txt
 #inline_index_openssl_valid_cn_list ()
 #{
-#	grep '^V.*$' "$EASYRSA_INDEX" | \
+#	"$EASYTLS_GREP" '^V.*$' "$EASYRSA_INDEX" | \
 #		sed -e 's`^.*/CN=``g' -e 's`/emailAddress=.*$``g'
 #}
 
 # Get common_name from inline file
 inline_crt_common_name ()
 {
-	inline_common_name="$(grep '^# Common name: .*$' "$inline_file")"
+	inline_common_name="$("$EASYTLS_GREP" '^# Common name: .*$' "$inline_file")"
 	inline_common_name="${inline_common_name##*name: }"
 }
 
 # Get serial number from inline file
 inline_crt_serial ()
 {
-	inline_serial="$(grep '^# X509 serial: .*$' "$inline_file")"
+	inline_serial="$("$EASYTLS_GREP" '^# X509 serial: .*$' "$inline_file")"
 	inline_serial="${inline_serial##*serial: }"
 }
 
@@ -1850,7 +1850,7 @@ openssl_crt_cn ()
 {
 	"$EASYRSA_OPENSSL" x509 -in "$crt_file" \
 		-noout -subject -nameopt sep_multiline | \
-		grep '^[[:blank:]]*CN=.*$' | \
+		"$EASYTLS_GREP" '^[[:blank:]]*CN=.*$' | \
 		sed 's/^[[:blank:]]*CN=//g'
 }
 
@@ -2111,7 +2111,7 @@ tlskey_index_update ()
 		easytls_verbose "  DEL: $old_record"
 
 		# Find old record - Do not $ terminate regex
-		grep -q "^${old_record}" "$EASYTLS_KEY_INDEX" || {
+		"$EASYTLS_GREP" -q "^${old_record}" "$EASYTLS_KEY_INDEX" || {
 			error_msg "tlskey_index_update del: Failed to find old record"
 			return 1
 			}
@@ -2228,17 +2228,17 @@ tls_crypt_v2_serial_number ()
 	generated_hash="${md_hash%% *}"
 
 	# Test it
-	printf '%s' "$generated_hash" | grep -q '[[:blank:][:punct:]]' && {
+	printf '%s' "$generated_hash" | "$EASYTLS_GREP" -q '[[:blank:][:punct:]]' && {
 		error_msg "tls_crypt_v2_serial_number - Invalid hash: $generated_hash"
 		return 1
 		}
-	printf '%s' "$generated_hash" | grep -q '^[[:xdigit:]]\+$' || {
+	printf '%s' "$generated_hash" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || {
 		error_msg "tls_crypt_v2_serial_number - Invalid hash: $generated_hash"
 		return 1
 		}
 
 	# Check for duplicate
-	grep -q "^${generated_hash}[[:blank:]]" "$EASYTLS_KEY_INDEX" && {
+	"$EASYTLS_GREP" -q "^${generated_hash}[[:blank:]]" "$EASYTLS_KEY_INDEX" && {
 		error_msg "SHA1 duplicate found! -- Please report this."
 		return 1
 		}
@@ -2267,11 +2267,11 @@ tlskey_index_full_name_to_x509_serial ()
 # tlskey verify serial number is valid
 verify_cert_serial ()
 {
-	printf '%s' "$cert_serial" | grep -q '[[:blank:][:punct:]]' && {
+	printf '%s' "$cert_serial" | "$EASYTLS_GREP" -q '[[:blank:][:punct:]]' && {
 		error_msg "verify_cert_serial - Invalid serial: $cert_serial"
 		return 1
 		}
-	printf '%s' "$cert_serial" | grep -q '^[[:xdigit:]]\+$' || {
+	printf '%s' "$cert_serial" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || {
 		error_msg "verify_cert_serial - Invalid serial: $cert_serial"
 		return 1
 		}
@@ -2280,11 +2280,11 @@ verify_cert_serial ()
 # tlskey verify serial number is valid
 verify_tlskey_serial ()
 {
-	printf '%s' "$tlskey_serial" | grep -q '[[:blank:][:punct:]]' && {
+	printf '%s' "$tlskey_serial" | "$EASYTLS_GREP" -q '[[:blank:][:punct:]]' && {
 		error_msg "verify_tlskey_serial - Invalid serial: $tlskey_serial"
 		return 1
 		}
-	printf '%s' "$tlskey_serial" | grep -q '^[[:xdigit:]]\+$' || {
+	printf '%s' "$tlskey_serial" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || {
 		error_msg "verify_tlskey_serial - Invalid serial: $tlskey_serial"
 		return 1
 		}
@@ -2293,7 +2293,7 @@ verify_tlskey_serial ()
 # # Verify that this key is no longer in use
 tlskey_verify_in_use ()
 {
-	grep -q "^.*[[:blank:]]${tlskey_serial}$" "$EASYTLS_INLINE_INDEX"
+	"$EASYTLS_GREP" -q "^.*[[:blank:]]${tlskey_serial}$" "$EASYTLS_INLINE_INDEX"
 }
 
 # Remove a TLS-Crypt-V2 Client key and update the tlskey-index
@@ -2393,10 +2393,10 @@ inline_renew ()
 	openssl_crt_serial
 
 	# Collect the attributes of .inline file
-	inline_is_base="$(grep -c '^# EasyTLS - File name base:.*$' "$inline_file")"
-	inline_is_tlsauth="$(grep -c '^<tls-auth>$' "$inline_file")"
-	inline_is_tlscrypt="$(grep -c '^<tls-crypt>$' "$inline_file")"
-	inline_is_tlscryptv2="$(grep -c '^<tls-crypt-v2>$' "$inline_file")"
+	inline_is_base="$("$EASYTLS_GREP" -c '^# EasyTLS - File name base:.*$' "$inline_file")"
+	inline_is_tlsauth="$("$EASYTLS_GREP" -c '^<tls-auth>$' "$inline_file")"
+	inline_is_tlscrypt="$("$EASYTLS_GREP" -c '^<tls-crypt>$' "$inline_file")"
+	inline_is_tlscryptv2="$("$EASYTLS_GREP" -c '^<tls-crypt-v2>$' "$inline_file")"
 
 	# Verify .inline is valid
 	[ $inline_is_base -eq 1 ] || \
@@ -2490,7 +2490,7 @@ inline_renew ()
 # Get current inline key direction
 inline_renew_key_direction ()
 {
-	grep '^key-direction [01]$' "$inline_file" | "$EASYTLS_AWK" '{print $2}'
+	"$EASYTLS_GREP" '^key-direction [01]$' "$inline_file" | "$EASYTLS_AWK" '{print $2}'
 }
 
 # Create inline credentials file from Easy-RSA PKI
@@ -3128,7 +3128,7 @@ hw_addr_hex_check ()
 		help_note="Hardware Address must be 12 digits exactly!"
 		return 1
 		}
-	printf '%s\n' "$temp_hw_addr" | grep -q '^[[:xdigit:]]\{12\}$' || {
+	printf '%s\n' "$temp_hw_addr" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\{12\}$' || {
 		help_note="Hardware Address must be hexidecimal digits!"
 		return 1
 		}
@@ -3358,17 +3358,17 @@ disabled_list_manager ()
 	openssl_crt_serial
 
 	# Check unique record from tlskey-index
-	grep -q \
+	"$EASYTLS_GREP" -q \
 		"${crt_serial}[[:blank:]]${name}[[:blank:]]${TLSKEY_SUBNAME}" \
 		"$EASYTLS_KEY_INDEX" || die "There is no tlskey for this certificate"
 
 	# Get tlskey-serial number from tlskey-index
 	tlskey_serial="$(tlskey_index_full_name_to_tls_serial)"
-	printf '%s' "$tlskey_serial" | grep -q '^[[:xdigit:]]\+$' || \
+	printf '%s' "$tlskey_serial" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || \
 		die "tlskey-serial is invalid: $tlskey_serial"
 
 	# Check disabled-list for this tlskey-serial
-	if grep -q "^${tlskey_serial}[[:blank:]]" "$EASYTLS_DISABLED_LIST"
+	if "$EASYTLS_GREP" -q "^${tlskey_serial}[[:blank:]]" "$EASYTLS_DISABLED_LIST"
 	then
 		is_disabled=1
 	else
@@ -3392,7 +3392,7 @@ disabled_list_manager ()
 				die "Failed to update disabled-list."
 
 			# Verify serial was added
-			grep -q "^${tlskey_serial}[[:blank:]]${crt_serial}[[:blank:]]" \
+			"$EASYTLS_GREP" -q "^${tlskey_serial}[[:blank:]]${crt_serial}[[:blank:]]" \
 				"$EASYTLS_DISABLED_LIST" || \
 				die "disabled-list error disable"
 
@@ -3413,7 +3413,7 @@ disabled_list_manager ()
 					}
 
 			# Verify serial was removed
-			grep -q "^${tlskey_serial}[[:blank:]]${crt_serial}[[:blank:]]" \
+			"$EASYTLS_GREP" -q "^${tlskey_serial}[[:blank:]]${crt_serial}[[:blank:]]" \
 				"$EASYTLS_DISABLED_LIST" && {
 					error_msg "Failed to update disabled-list"
 					exit 99
@@ -3445,7 +3445,7 @@ disabled_list_manager ()
 # Search disabled-list for serial number
 disabled_list_serial_search ()
 {
-	grep -c "^${crt_serial}[[:blank:]]${name}$" "$EASYTLS_DISABLED_LIST"
+	"$EASYTLS_GREP" -c "^${crt_serial}[[:blank:]]${name}$" "$EASYTLS_DISABLED_LIST"
 }
 
 # Update disabled-list footer and hash
@@ -4657,7 +4657,7 @@ interactive_verify_cert ()
 		return 1
 		}
 
-	grep -q "TLS Web $cert_type" "$cert_file" || {
+	"$EASYTLS_GREP" -q "TLS Web $cert_type" "$cert_file" || {
 		printf '\n%s\n' "  ERROR: Certificate must be a $cert_type"
 		return 1
 		}
@@ -4667,8 +4667,8 @@ interactive_verify_cert ()
 interactive_auto_cert_type ()
 {
 	unset cert_type
-	grep -q 'TLS Web Server' "$cert_file" && is_server=1
-	grep -q 'TLS Web Client' "$cert_file" && is_client=1
+	"$EASYTLS_GREP" -q 'TLS Web Server' "$cert_file" && is_server=1
+	"$EASYTLS_GREP" -q 'TLS Web Client' "$cert_file" && is_client=1
 	[ $is_server ] && [ $is_client ] && \
 		die "Unsupported certificate: Server&Client"
 	[ $is_server ] && cert_type='Server'
@@ -5181,7 +5181,7 @@ interactive_x509_method ()
 			if [ -n "$ia_answer" ]
 			then
 				opt_preload_id="$ia_answer"
-				printf '%s' "$opt_preload_id" | grep -q '^[[:xdigit:]]\{40\}$' || {
+				printf '%s' "$opt_preload_id" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\{40\}$' || {
 					error_msg "Invalid CA-ID"
 					continue
 					}
@@ -5474,11 +5474,11 @@ save_wiscii_hash ()
 	[ "$counted_wiscii" = "$bottled_wiscii" ] && return 0
 
 	# Test it here Only!
-	printf '%s' "$counted_wiscii" | grep -q '[[:blank:][:punct:]]' && {
+	printf '%s' "$counted_wiscii" | "$EASYTLS_GREP" -q '[[:blank:][:punct:]]' && {
 		error_msg "save_wiscii_hash - Invalid hash: $counted_wiscii"
 		return 1
 		}
-	printf '%s' "$counted_wiscii" | grep -q '^[[:xdigit:]]\+$' || {
+	printf '%s' "$counted_wiscii" | "$EASYTLS_GREP" -q '^[[:xdigit:]]\+$' || {
 		error_msg "save_wiscii_hash - Invalid hash: $counted_wiscii"
 		return 1
 		}
@@ -5535,7 +5535,7 @@ external_deps ()
 	EASYTLS_CAT='cat' # Checked by Easy-RSA3
 	EASYTLS_CP='cp' # Checked by Easy-RSA3
 	EASYTLS_DATE='date'
-	easytls_grep='grep'
+	EASYTLS_GREP='grep'
 	#easytls_ls='ls' # Not used in Easy-TLS
 	easytls_mkdir='mkdir' # Checked by Easy-RSA3
 	easytls_mktemp='mktemp'
@@ -5546,7 +5546,7 @@ external_deps ()
 
 	# Check the ones Easy-RSA3 fails to..
 	"$EASYTLS_DATE"             > /dev/null || die 'Missing file: date'
-	$easytls_grep --version   > /dev/null || die 'grep error'
+	"$EASYTLS_GREP" --version   > /dev/null || die 'Missing file: grep'
 	$easytls_mktemp --version > /dev/null || die 'mktemp error'
 	$easytls_sed --version    > /dev/null || die 'sed error'
 }
