Inter-active Menu: Fix Remove TLS-Crypt-V2 Client --sub-key-name
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -4044,9 +4044,17 @@ interactive_remove ()
 		# Set option --sub-key-name
 		interactive_sub_key_name
 
-		key_file="${EASYTLS_PKI}/${opt_name}-tls-crypt-v2.key"
-		[ -f "$key_file" ] || \
-			die "TLS-Crypt-V2 key does not exist: $key_file"
+		# Append --sub-key-name if specifies
+		if [ "$TLSKEY_SUBNAME" = 'NOSUBKEY' ]
+		then
+			key_name="${opt_name}"
+		else
+			key_name="${opt_name}-$TLSKEY_SUBNAME"
+		fi
+
+		# Set file names
+		key_file="${EASYTLS_PKI}/${key_name}-tls-crypt-v2.key"
+		metadata_debug="${EASYTLS_MD_DIR}/${key_name}-tls-crypt-v2.metadata"
 
 		# Confirm
 		interactive_remove_warning 'remove-tls-crypt-v2-client-key'
@@ -4054,11 +4062,18 @@ interactive_remove ()
 		# Print command
 		interactive_show_cmd
 
+		# Enable internal batch_mode
+		batch_mode=1
+
 		# Remove key
 		remove_tlskey "$opt_name" || {
 			error_msg '**Remove TLS-key failed'
 			return 1
 			}
+
+		# Disable internal batch_mode
+		unset batch_mode
+
 		printf '\n%s\n' "  * TLS-Crypt-V2 Client key removed: $key_file"
 	;;
 	3)	# Remove Server inline-file
@@ -4074,6 +4089,9 @@ interactive_remove ()
 
 		inline_file="${EASYTLS_PKI}/${opt_name}.inline"
 		[ -f "$inline_file" ] || die "Missing inline-file: $inline_file"
+
+		# Confirm
+		interactive_remove_warning 'remove-tls-crypt-v2-server-inline'
 
 		# Print command
 		interactive_show_cmd
@@ -4244,6 +4262,8 @@ interactive_remove ()
 # Issue a remove warning
 interactive_remove_warning ()
 {
+	[ $EASYTLS_BATCH ] || \
+		printf '\n%s\n%s\n%s' '  ###########' '  # WARNING #' '  ###########'
 	case $1 in
 	remove-tls-auth-key)
 	# TLS-Auth key
@@ -4282,25 +4302,56 @@ interactive_remove_warning ()
 	remove-tls-crypt-v2-client-key)
 	# TLS-Crypt-V2 Client key
 		[ -f "$key_file" ] || die "Missing file: $key_file"
+		confirm 'Are you sure you want to delete this key (CANNOT be undone): ' \
+			'yes' "
+* If you remove a TLS-Crypt-V2 Client key then you can easily
+  build a new one from the same TLS-Crypt-V2 Server key.
+
+  Key file:
+  * $key_file"
 	;;
 	remove-tls-auth-inline)
 	# TLS-Auth inline
 		[ -f "$inline_file" ] || die "Missing file: $inline_file"
+		confirm 'Are you sure you want to delete this inline-file: ' \
+			'yes' "
+* When you remove an inline-file you can easily build a new one.
+
+  Inline file:
+  * $inline_file"
 	;;
 	remove-tls-crypt-inline)
 	# TLS-Crypt inline
 		[ -f "$inline_file" ] || die "Missing file: $inline_file"
+		confirm 'Are you sure you want to delete this inline-file: ' \
+			'yes' "
+* When you remove an inline-file you can easily build a new one.
+
+  Inline file:
+  * $inline_file"
 	;;
 	remove-tls-crypt-v2-server-inline)
 	# TLS-Crypt-V2 Server inline
 		[ -f "$inline_file" ] || die "Missing file: $inline_file"
+		confirm 'Are you sure you want to delete this inline-file: ' \
+			'yes' "
+* When you remove an inline-file you can easily build a new one.
+
+  Inline file:
+  * $inline_file"
 	;;
 	remove-tls-crypt-v2-client-inline)
 	# TLS-Crypt-V2 Client inline
 		[ -f "$inline_file" ] || die "Missing file: $inline_file"
+		confirm 'Are you sure you want to delete this inline-file: ' \
+			'yes' "
+* When you remove an inline-file you can easily build a new one.
+
+  Inline file:
+  * $inline_file"
 	;;
 	*)
-		die "Cannot issue warning for unknown option: $1"
+		die "Cannot issue a warning for unknown option: $1"
 	;;
 	esac
 } # => interactive_remove_warning ()
@@ -4544,6 +4595,11 @@ interactive_sub_key_name ()
 		# Otherwise this returns a hidden error
 		:
 	fi
+
+	[ "$TLSKEY_SUBNAME" = 'NOSUBKEY' ] || {
+	key_file="$EASYTLS_PKI/$cli_name-$TLSKEY_SUBNAME-tls-crypt-v2.key"
+	metadata_debug="$EASYTLS_MD_DIR/$cli_name-$TLSKEY_SUBNAME-tls-crypt-v2.metadata"
+	}
 }
 
 # Set key direction
