Verify "$#" meets minimum requirements per function
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -22,6 +22,7 @@
 # + OpenVPN Version 2.X
 #
 
+
 # Help/usage output to stdout
 usage()
 {
@@ -55,7 +56,7 @@ Here is the list of commands available with a short syntax reminder. Use the
   inline-tls-crypt-v2 <filename_base> [ cmd-opts ]
   inline-remove <filename_base>
   inline-renew <filename_base> [ cmd-opts ]
-  inline-status [update?]
+  inline-status [ cmd-opts ]
   test-inline (Requires root) (TODO)
 "
 
@@ -106,7 +107,8 @@ cmd_help()
       for VPN node <filename_base> using the Easy-TLS TLS auth file
       <key_direction> either '0' (For server) or '1' (For client)"
 			opts="
-        nokey   - do not require an x509 key (default: key is required)" ;;
+        nokey   - do not require an x509 key (default: key is required)
+	nodir   - do not add 'key-direction 0|1'" ;;
 		inline-tls-crypt) text="
   inline-tls-crypt <filename_base> [ cmd-opts ]
       Create a complete OpenVPN node package from Easy-RSA and Easy-TLS files
@@ -128,9 +130,10 @@ cmd_help()
 			opts="
         nokey   - do not require an x509 key (default: key is required)" ;;
 		inline-status) text="
-  inline-status [update]
-      Compare Easy-RSA certificate(s) to Easy-TLS inline(s) status
-      update - rebuild inline-index.tls (TODO)" ;;
+  inline-status [ cmd-opts ]
+      Compare Easy-RSA certificate(s) to Easy-TLS inline(s) status"
+			opts="
+        rebuild - rebuild inline-index.tls (TODO)" ;;
 		options)
 			opt_usage ;;
 		"")
@@ -313,8 +316,9 @@ verify_openvpn ()
 # Verify Openvpn version, 2.5 required for TLS crypt v2, 2.4 required for TLS crypt v1
 verify_openvpn_version ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <ovpn_ver_req_maj>"
+
 	ovpn_ver_req_maj="$1"
-	[ -z "$ovpn_ver_req_maj" ] && die "Openvpn Major Version required not set."
 	ovpn_ver_str="$("$EASYTLS_OPENVPN" --version | grep ^OpenVPN | awk '{print $2}')"
 	ovpn_ver_ints="$(printf "%s" "$ovpn_ver_str" | sed "s/[^0123456789]/\ /g")"
 
@@ -402,8 +406,9 @@ inline_status ()
 	# List mismatches
 	status_easytls_mismatch
 
-	# Wipe out spurious error code
+	# Wipe out spurious error code from above test
 	return 0
+
 } #=> inline_status ()
 
 # Print Valid certs from Easy-RSA
@@ -485,6 +490,8 @@ status_easytls_mismatch ()
 # Keep an index file for inline certs to manage revoke/renew
 update_inline_index ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <update_index_action>"
+
 	update_index_action="$1"
 	easytls_index_backup="$EASYTLS_INLINE_INDEX.bkp"
 	easytls_index_temp="$EASYTLS_INLINE_INDEX.tmp"
@@ -516,6 +523,8 @@ update_inline_index ()
 # Remove .inline file
 inline_remove ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
+
 	name="$1"
 	inline_file="$EASYTLS_PKI/$name.inline"
 
@@ -539,6 +548,10 @@ inline_remove ()
 # Renew .inline file
 inline_renew ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
+
+	verify_ca_init
+
 	# Disable completion notices from sub processes
 	no_exit_note=1
 
@@ -621,7 +634,8 @@ inline_renew ()
 # Create inline credentials file from Easy-RSA PKI
 inline_base ()
 {
-	# TODO: Improve build_inline integration. eg: renew/revoke
+	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
+
 	verify_ca_init
 
 	name="$1"
@@ -708,7 +722,10 @@ $help_note"
 # Append TLS auth file to base file
 inline_tls_auth ()
 {
+	[ $# -ge 2 ] || die "Required option(s): <filename_base> <key_direction>"
+
 	verify_ca_init
+
 	name="$1"
 	key_dir="$2"
 	shift 2
@@ -717,6 +734,7 @@ inline_tls_auth ()
 	while [ -n "$1" ]; do
 		case "$1" in
 			nokey) cmd_opts="$cmd_opts nokey" ;;
+			nodir) unsupported_option "nodir" ;;
 			*) warn "Ignoring unknown command option: '$1'" ;;
 		esac
 		shift
@@ -756,7 +774,10 @@ inline_tls_auth ()
 # Append TLS crypt file to base file
 inline_tls_crypt_v1 ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
+
 	verify_ca_init
+
 	name="$1"
 	shift
 
@@ -792,12 +813,15 @@ inline_tls_crypt_v1 ()
 	# Wipe out spurious error code from above test
 	return 0
 
-} # => inline_tls_crypt ()
+} # => inline_tls_crypt_v1 ()
 
 # Append TLS crypt v2 file to base file
 inline_tls_crypt_v2 ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
+
 	verify_ca_init
+
 	name="$1"
 	shift
 
@@ -835,6 +859,21 @@ inline_tls_crypt_v2 ()
 	return 0
 
 } # => inline_tls_crypt_v2 ()
+
+# Non-negotiable notices
+unsupported_option ()
+{
+	case $1 in
+		nodir)
+	print "'key-direction' is required to be 0 for server and 1 for client,"
+	print "if that is not suitable for you then do not use this script."
+	;;
+		*)
+	print "You forgot the option name .."
+	;;
+	esac
+	exit 9
+} # => unsupported_option ()
 
 # Check that the requested certificate is not revoked before inline
 inline_cert_status ()
@@ -897,6 +936,8 @@ build_tls_crypt_v1 ()
 # Create TLS crypt v2 server file
 build_tls_crypt_v2_server ()
 {
+	[ $# -ge 1 ] || die "Required option(s): <server_filename_base>"
+
 	# Requires openvpn version 2.5
 	verify_openvpn_version 5
 
@@ -906,8 +947,6 @@ build_tls_crypt_v2_server ()
 	srv_name="$1"
 	srv_cert="$EASYRSA_PKI/issued/$srv_name.crt"
 	out_file="$EASYTLS_PKI/tls-crypt-v2-$srv_name.key"
-
-	[ -n "$srv_name" ] || die "Server name required."
 
 	[ -f "$srv_cert" ] || \
 		die "Easy-TLS requires that the Easy-RSA certificate has been created.
@@ -929,6 +968,9 @@ Missing file: $srv_cert"
 # Create TLS crypt v2 client file
 build_tls_crypt_v2_client ()
 {
+	[ $# -ge 2 ] || \
+		die "Required option(s): <server_filename_base> <client_filename_base>"
+
 	# Requires openvpn version 2.5
 	verify_openvpn_version 5
 
@@ -940,8 +982,6 @@ build_tls_crypt_v2_client ()
 	cli_name="$2"
 	cli_cert="$EASYRSA_PKI/issued/$cli_name.crt"
 
-	[ -n "$srv_name" ] || die "Server name required."
-	[ -n "$cli_name" ] || die "Client name required."
 	[ "$srv_name" = "$cli_name" ] && \
 		die "Server name cannot be the same as the client name."
 
@@ -1053,7 +1093,7 @@ set_var()
 # Set the Easy-TLS version
 easy_tls_version ()
 {
-	EASYTLS_VERSION="1.0"
+	EASYTLS_VERSION="1.01"
 	print "Easy-TLS version: $EASYTLS_VERSION"
 } # => easy_tls_version ()
 
