Inter-active menu improvements and switch config to master hash
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -1169,7 +1169,7 @@ config_version ()
 
 	# Save me ! - Changes have been made
 	if [ -n "${save_me}" ]; then
-		save_wiscii_hash || return 1 # die "Error hashing config."
+		save_master_hash || return 1 # die "Error hashing config."
 	fi
 	unset -v flash_config save_me cfg_opt cfg_val
 } # => config_version ()
@@ -2726,9 +2726,7 @@ inline_index_update ()
 		}
 
 	easytls_verbose "Inline Index Update complete!"
-
-	# Inline Index Update complete
-	return 0
+	update_master_hash=1
 } # => inline_index_update ()
 
 # Verify current inline-index hash
@@ -3041,7 +3039,7 @@ remove_group_inline ()
 
 	# Move
 	if [ -z "${force_remove}" ]; then
-		"${EASYTLS_MV}" "${inline_file}" "${inline_file}-deleteme" || \
+		"${EASYTLS_MV}" "${inline_file}" "${inline_file}-deleted" || \
 			die "Failed to move: ${inline_file}"
 	else
 		"${EASYTLS_MV}" "${inline_file}" "${inline_file}-badhash" || \
@@ -3052,13 +3050,13 @@ remove_group_inline ()
 	if inline_index_update del; then
 		# Remove
 		if [ -z "${force_remove}" ]; then
-			"${EASYTLS_RM}" "${inline_file}-deleteme" || \
+			"${EASYTLS_RM}" "${inline_file}-deleted" || \
 				die "Failed to remove: ${inline_file}"
 		fi
 	else
 		# Undo move
 		if [ -z "${force_remove}" ]; then
-			"${EASYTLS_MV}" "${inline_file}-deleteme" "${inline_file}" || \
+			"${EASYTLS_MV}" "${inline_file}-deleted" "${inline_file}" || \
 				die "Failed to restore: ${inline_file}"
 		else
 			"${EASYTLS_MV}" "${inline_file}-badhash" "${inline_file}" || \
@@ -3080,7 +3078,7 @@ remove_group_inline ()
 		notice "Inline file renamed to: ${inline_file}-badhash"
 	fi
 	easytls_verbose
-} # => remove_inline ()
+} # => remove_group_inline ()
 
 # Remove metadata from inline file
 remove_metadata ()
@@ -6245,7 +6243,7 @@ interactive_build ()
 			}
 
 		# save me! - Changes have been made
-		save_wiscii_hash || die "Master hash save failed"
+		save_master_hash || die "Master hash save failed"
 
 		# Request inline
 		cmd_line="inline-tls-crypt-v2 $opt_server_name"
@@ -6380,7 +6378,7 @@ interactive_build ()
 		unset -v require_batch
 
 		# save me! - Changes have been made
-		save_wiscii_hash || die "Master hash save failed"
+		save_master_hash || die "Master hash save failed"
 
 		# Request inline
 		cmd_line="inline-tls-crypt-v2 $opt_client_name"
@@ -6671,12 +6669,13 @@ interactive_remove ()
 	ia_question_text='
   [1] TLS-Crypt-V2 Client inline-file
   [2] TLS-Crypt-V2 Client key
-  [3] TLS-Crypt-V2 GROUP Client key
-  [4] TLS-Crypt-V2 Server inline-file
-  [5] TLS-Crypt-V2 Server key
-  [6] TLS-Crypt-V1 key
-  [7] TLS-Auth key
-  [8] Client Inline TLS-Crypt-V2 metadata
+  [3] TLS-Crypt-V2 GROUP Client inline-file
+  [4] TLS-Crypt-V2 GROUP Client key
+  [5] TLS-Crypt-V2 Server inline-file
+  [6] TLS-Crypt-V2 Server key
+  [7] TLS-Crypt-V1 key
+  [8] TLS-Auth key
+  [9] Client Inline TLS-Crypt-V2 metadata
 
   Select the type of file to remove:'
 	interactive_question
@@ -6720,7 +6719,7 @@ interactive_remove ()
 			"  * TLS-Crypt-V2 Client inline removed: $key_file"
 
 		# save me! - Changes have been made
-		save_wiscii_hash || die "Master hash save failed"
+		save_master_hash || die "Master hash save failed"
 
 		# Request remove_tlskey
 		default='Y'
@@ -6823,18 +6822,124 @@ interactive_remove ()
 		"$EASYTLS_PRINTF" '\n%s\n' \
 			"  * TLS-Crypt-V2 Client key removed: $key_file"
 	;;
-	3)	# Remove GROUP client key
-		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-V2 GROUP Client key'
-		cmd_line="${cmd_line}-tlskey"
+	3)	# Remove GROUP Client inline-file
+		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-v2 Client inline-file'
+		cmd_line="${cmd_line}-group-inline"
 
-		# Set Client name
+		# Set commonName
 		opt_name=""
 		cert_type='Client'
 		interactive_common_name
 		opt_name="$common_name"
+		inline_file="${EASYTLS_PKI}/${opt_name}.inline"
+		key_file="${EASYTLS_PKI}/${opt_name}-tls-crypt-v2.key"
+		metadata_debug="${EASYTLS_MDATA_D}/${opt_name}-tls-crypt-v2.metadata"
+
+		# Group name
+		interactive_gkey_name
+		inline_file="${EASYTLS_PKI}/${opt_name}-${opt_gkey_name}.inline"
+		opt_name="${opt_name}-${opt_gkey_name}"
 
 		# Set option --sub-key-name
-		interactive_sub_key_name
+		#interactive_sub_key_name
+
+		# Confirm
+		interactive_remove_warning 'remove-tls-crypt-v2-group-client-inline'
+
+		# Print command
+		interactive_show_cmd
+
+		# Enable internal require_batch
+		require_batch=1
+
+		# Remove .inline
+		remove_inline "$opt_name" || {
+			error_msg '**Remove inline-file failed'
+			return 1
+			}
+
+		# Disable internal require_batch
+		unset -v require_batch
+
+		"$EASYTLS_PRINTF" '\n%s\n' \
+			"  * TLS-Crypt-V2 Client inline removed: $key_file"
+
+		# save me! - Changes have been made
+		save_master_hash || die "Master hash save failed"
+
+		# Request remove_tlskey
+		default='Y'
+		ia_question_help="
+* Do you want to remove the corresponding TLS-Crypt-V2 key ?
+
+  * Default: $default"
+		ia_question_text='
+  Enter (y)es or (n)o:'
+		while :
+		do
+			interactive_question
+			ia_answer="${ia_answer:-$default}"
+			case "$ia_answer" in
+				Y|y|Yes|yes|YES)
+					remove_inline_and_tlskey=1
+					break
+				;;
+				N|n|No|no|NO)
+					break
+				;;
+				*)
+					: # Ignore
+				;;
+			esac
+		done
+
+		# Invoke remove_tlskey
+		if [ -n "${remove_inline_and_tlskey}" ]
+		then
+			# Print command
+			cmd_line="remove-group-tlskey $opt_name"
+			[ "$TLSKEY_SUBNAME" = 'NOSUBKEY' ] || \
+				cmd_line="--sub-key-name=${sub_key_name} ${cmd_line}"
+			interactive_show_cmd
+
+			# Enable internal require_batch
+			require_batch=1
+
+			# Remove TLS key
+			remove_group_tlskey "$opt_gkey_name" || {
+				error_msg '**Remove TLS-key failed'
+				return 1
+				}
+
+			# Disable internal require_batch
+			unset -v require_batch
+
+			"$EASYTLS_PRINTF" '\n%s\n' \
+				"  * TLS-Crypt-V2 GROUP Client key removed: $key_file"
+		else
+			"$EASYTLS_PRINTF" '\n%s\n' \
+			'  * Inline-file removed. TLS-Crypt-V2 GROUP key is unchanged.'
+			easytls_verbose
+		fi
+	;;
+	4)	# Remove GROUP client key
+		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-V2 GROUP Client key'
+		cmd_line="${cmd_line}-tlskey"
+
+		# Group name
+		opt_name=""
+		interactive_gkey_name
+		key_file="${EASYTLS_PKI}/${opt_gkey_name}-tls-crypt-v2.key"
+		opt_name="${opt_gkey_name}"
+
+		# Set Client name
+		#opt_name=""
+		#cert_type='Client'
+		#interactive_common_name
+		#opt_name="$common_name"
+
+		# Set option --sub-key-name
+		#interactive_sub_key_name
 
 		# Append --sub-key-name if specifies
 		if [ "$TLSKEY_SUBNAME" = 'NOSUBKEY' ]
@@ -6843,10 +6948,6 @@ interactive_remove ()
 		else
 			key_name="${opt_name}-$TLSKEY_SUBNAME"
 		fi
-
-		# Set file names
-		key_file="${EASYTLS_PKI}/${key_name}-tls-crypt-v2.key"
-		metadata_debug="${EASYTLS_MDATA_D}/${key_name}-tls-crypt-v2.metadata"
 
 		# Confirm
 		interactive_remove_warning 'remove-tls-crypt-v2-group-client-key'
@@ -6869,7 +6970,7 @@ interactive_remove ()
 		"$EASYTLS_PRINTF" '\n%s\n' \
 			"  * TLS-Crypt-V2 GROUP Client key removed: $key_file"
 	;;
-	4)	# Remove Server inline-file
+	5)	# Remove Server inline-file
 		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-v2 Server inline-file'
 		cmd_line="${cmd_line}-inline"
 
@@ -6902,7 +7003,7 @@ interactive_remove ()
 		unset -v require_batch
 
 		# save me! - Changes have been made
-		save_wiscii_hash || die "Master hash save failed"
+		save_master_hash || die "Master hash save failed"
 
 		# Request remove_tlskey
 		cmd_line="remove-tlskey $opt_name"
@@ -6967,7 +7068,7 @@ interactive_remove ()
 			easytls_verbose
 		fi
 	;;
-	5)	# Remove Server key
+	6)	# Remove Server key
 		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-V2 Server key'
 		cmd_line="${cmd_line}-tlskey"
 
@@ -7001,7 +7102,7 @@ interactive_remove ()
 		"$EASYTLS_PRINTF" '\n%s\n' \
 			"  * TLS-Crypt-V2 Server key removed: $key_file"
 	;;
-	6)	# tls-crypt key
+	7)	# tls-crypt key
 		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt key'
 		cmd_line="${cmd_line}-tlskey"
 
@@ -7027,7 +7128,7 @@ interactive_remove ()
 
 		"$EASYTLS_PRINTF" '\n%s\n' "  * TLS-Crypt key removed: $key_file"
 	;;
-	7)	# tls-auth key
+	8)	# tls-auth key
 		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Auth key'
 		cmd_line="${cmd_line}-tlskey"
 
@@ -7053,7 +7154,7 @@ interactive_remove ()
 
 		"$EASYTLS_PRINTF" '\n%s\n' "  * TLS-Auth key removed: $key_file"
 	;;
-	8)	# inline metadata
+	9)	# inline metadata
 		"$EASYTLS_PRINTF" '\n%s\n' '* Remove TLS-Crypt-v2 Client inline-metadata'
 		cmd_line="${cmd_line}-metadata"
 
@@ -7186,6 +7287,16 @@ interactive_remove_warning ()
   * $inline_file"
 	;;
 	remove-tls-crypt-v2-client-inline)
+		# TLS-Crypt-V2 Client inline
+		[ -f "$inline_file" ] || missing_file "$inline_file"
+		confirm 'Are you sure you want to delete this inline-file: ' \
+			'yes' "
+* When you remove an inline-file you can easily build a new one.
+
+  Inline file:
+  * $inline_file"
+	;;
+	remove-tls-crypt-v2-group-client-inline)
 		# TLS-Crypt-V2 Client inline
 		[ -f "$inline_file" ] || missing_file "$inline_file"
 		confirm 'Are you sure you want to delete this inline-file: ' \
@@ -7559,9 +7670,10 @@ interactive_gkey_name ()
 			interactive_try_again "This field CANNOT be empty"
 			continue
 			}
-		gkey_file="${EASYTLS_PKI}/${opt_gkey_name}.key"
-		[ -f "${gkey_file}" ] || break
-		print "* This key file already exists: ${gkey_file}"
+		#gkey_file="${EASYTLS_PKI}/${opt_gkey_name}.key"
+		break
+		#[ -f "${gkey_file}" ] || break
+		#print "* This key file already exists: ${gkey_file}"
 	done
 } # => interactive_gkey_name ()
 
