Replace die() in update_inline_index() and capture errors when called
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -1340,13 +1340,15 @@ inline_expire ()
 # Keep an inline-index file for inline certs to manage revoke/renew
 inline_index_update ()
 {
-	[ $# -ge 1 ] || die "Required option(s): <update_index_action>"
 	update_index_action="$1"
 
 	verify_tls_init
 
 	# Verify inline-index Hash
-	inline_index_verify_index_hash || die "inline-index is corrupt"
+	inline_index_verify_index_hash || {
+		error_msg "inline-index is corrupt"
+		return 1
+		}
 
 	case "$update_index_action" in
 	add)
@@ -1356,12 +1358,17 @@ inline_index_update ()
 		inline_crt_serial
 
 		# If this HASH is set then another function is responsible for it
+		# TODO: Is this necessary?
 		[ "$inline_hash" ] && \
 			die "Do not allow a HASH here: inline_index_update add"
 
-		# Create new HASH
-		generate_file_hash "$inline_file" || \
-			die "inline_index_update add: Failed to hash: $inline_file"
+		# Create new inline file HASH
+		generate_file_hash "$inline_file" || {
+			error_msg "inline_index_update add: Failed to hash: $inline_file"
+			return 1
+			}
+
+		# Set new inline file HASH
 		current_inline_hash="$generated_hash"
 
 		# Create new record
@@ -1372,8 +1379,12 @@ inline_index_update ()
 		tlskey_serial="${tlskey_serial:-'n/a'}"
 		[ $EASYTLS_TLSCV2_SUBKNAME ] && \
 			new_record="$new_record $EASYTLS_TLSCV2_SUBKNAME $tlskey_serial"
-		printf "%s\n" "$new_record" >> "$EASYTLS_INLINE_INDEX" || \
-			die "Failed to update $EASYTLS_INLINE_INDEX"
+
+		# Write new record
+		printf "%s\n" "$new_record" >> "$EASYTLS_INLINE_INDEX" || {
+			error_msg "Failed to update $EASYTLS_INLINE_INDEX"
+			return 1
+			}
 
 		easytls_verbose "  ADD: $new_record"
 	;;
@@ -1384,26 +1395,33 @@ inline_index_update ()
 
 		# Find old record
 		grep -q "^${old_record}" "$EASYTLS_INLINE_INDEX" || {
-			help_note="Missing record: $old_record"
-			die "inline_index_update del: Failed to find old record"
+			error_msg "inline_index_update del: Failed to find: $old_record"
+			return 1
 			}
 
 		# Remove old record
 		easytls_verbose "  DEL: $old_record"
 		sed -i -e "/^${old_record}.*$/d" "$EASYTLS_INLINE_INDEX" || {
-			help_note="Missing record: $old_record"
-			die "inline_index_update del: Failed write"
+			error_msg "inline_index_update del: Failed write"
+			return 1
 			}
 	;;
 	*)
-		die "Unknown index action: $update_index_action"
+		error_msg "Unknown index action: $update_index_action"
+		return 1
 	;;
 	esac
 
 	# Keep a hash of the inline-index
-	inline_index_save_hash || die "Failed to update inline-index hash"
+	inline_index_save_hash || {
+		error_msg "Failed to update inline-index hash"
+		return 1
+		}
 
 	easytls_verbose "Inline Index Update complete!"
+
+	# Inline Index Update complete
+	return 0
 } # => inline_index_update ()
 
 # Verify current inline-index hash
@@ -1713,7 +1731,7 @@ inline_remove ()
 	rm "$inline_file" || die "Failed to remove: $inline_file"
 
 	# Update the index first
-	inline_index_update del
+	inline_index_update del || die "Failed to update inline-index"
 
 	# Inline file and record deleted - Forget the HASH
 	# Otherwise 'inline_renew add' still has the HASH
@@ -1842,6 +1860,7 @@ inline_index_rebuild ()
 			}
 
 		# Add the record
+		# TODO: Add die here
 		[ $add_inline_record ] && inline_index_update add
 		:
 	done
@@ -1876,14 +1895,14 @@ tlskey_index_update ()
 
 	verify_tls_init
 
+	# Verify tlskey-index Hash
+	tlskey_index_verify_hash || {
+		error_msg "tlskey-index is corrupt"
+		return 1
+		}
+
 	case "$update_index_action" in
 	add)
-		# Verify tlskey-index Hash
-		tlskey_index_verify_hash || {
-			error_msg "tlskey-index is corrupt"
-			return 1
-			}
-
 		# Create new record
 		new_record="$tlskey_serial $crt_serial $cli_name $EASYTLS_TLSCV2_SUBKNAME"
 
@@ -1896,12 +1915,6 @@ tlskey_index_update ()
 		easytls_verbose "  ADD: $new_record"
 	;;
 	del)
-		# Verify tlskey-index Hash
-		tlskey_index_verify_hash || {
-			error_msg "tlskey-index is corrupt"
-			return 1
-			}
-
 		# Note: tlskey_serial is unique, regardless of --sub-key-name
 		# Identify old record
 		old_record="${tlskey_serial}[[:blank:]].*[[:blank:]]${name}[[:blank:]]"
@@ -2271,11 +2284,6 @@ inline_base ()
 		return 1
 		}
 
-	# Update INLINE index
-	# Only if this is the root caller
-	# inline-base is never the rools caller
-	#[ ! $silent_base ] && inline_index_update add
-
 	easytls_verbose "Inline base file created: $inline_file"
 
 	# explicitly return success for callers
@@ -2336,7 +2344,7 @@ inline_tls_auth ()
 	} >> "$inline_file" || die "Failed to create inline file: $inline_file"
 
 	# Hash inline file and add hash to index
-	inline_index_update add
+	inline_index_update add || die "Failed to update inline-index"
 
 	[ ! $silent_inline ] && \
 		notice "Inline TLS auth file created: $inline_file"
@@ -2384,7 +2392,7 @@ inline_tls_crypt_v1 ()
 	} >> "$inline_file" || die "Failed to create inline file: $inline_file"
 
 	# Hash inline file and add hash to index
-	inline_index_update add
+	inline_index_update add || die "Failed to update inline-index"
 
 	[ ! $silent_inline ] && \
 		notice "Inline TLS crypt file created: $inline_file"
@@ -2470,7 +2478,7 @@ inline_tls_crypt_v2 ()
 	} >> "$inline_file" || die "Failed to create inline file: $inline_file"
 
 	# Hash inline file and add hash to index
-	inline_index_update add
+	inline_index_update add || die "Failed to update inline-index"
 
 	[ ! $silent_inline ] && \
 		notice "Inline TLS crypt v2 file created: $inline_file"
