inline_tls_crypt_v1() - Use {} for variable names
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easytls b/easytls
--- a/easytls
+++ b/easytls
@@ -3029,7 +3029,7 @@ inline_tls_auth ()
 	"${EASYTLS_CAT}" "${inline_base}" "${inline_temp}" > "${inline_file}"
 
 	# Remove temp files
-	rm -f "${inline_base}" "${inline_temp}"
+	"${EASYTLS_RM}" -f "${inline_base}" "${inline_temp}"
 
 	# Hash inline file and add hash to index
 	inline_index_update add || die "Failed to update inline-index"
@@ -3047,58 +3047,56 @@ inline_tls_crypt_v1 ()
 {
 	[ $# -ge 1 ] || die "Required option(s): <filename_base>"
 
-	name="$1"
+	name="${1}"
 	shift
 
 	cmd_opts=""
-	while [ -n "$1" ]; do
-		case "$1" in
-			add-dh) cmd_opts="$cmd_opts add-dh" ;;
-			no-key) cmd_opts="$cmd_opts no-key" ;;
-			*) warn "Ignoring unknown command option: '$1'" ;;
+	while [ -n "${1}" ]; do
+		case "${1}" in
+			add-dh) cmd_opts="${cmd_opts} add-dh" ;;
+			no-key) cmd_opts="${cmd_opts} no-key" ;;
+			*) warn "Ignoring unknown command option: '${1}'" ;;
 		esac
 		shift
 	done
 
-	tlskey_file="$EASYTLS_PKI/tls-crypt.key"
-	inline_file="$EASYTLS_PKI/$name.inline"
-	inline_temp="$EASYTLS_PKI/$name.temp"
-	inline_base="$EASYTLS_PKI/$name.base"
+	tlskey_file="${EASYTLS_PKI}/tls-crypt.key"
+	inline_file="${EASYTLS_PKI}/${name}.inline"
+	inline_temp="${EASYTLS_PKI}/${name}.temp"
+	inline_base="${EASYTLS_PKI}/${name}.base"
 
 	# Check inline file does not exist
-	[ -f "$inline_file" ] && {
+	[ -f "${inline_file}" ] && {
 		help_note="Use 'easytls remove' to delete the old inline file."
-		die "Inline file already exists: $inline_file"
+		die "Inline file already exists: ${inline_file}"
 		}
 
 	# Check tls-crypt key exists
-	[ -f "$tlskey_file" ] || {
+	[ -f "${tlskey_file}" ] || {
 		help_note="Use 'easytls build' to create a TLS-Crypt-V1 key."
-		die "TLS key file does not exist: $tlskey_file"
+		die "TLS key file does not exist: ${tlskey_file}"
 		}
 
 	# Inline base file
-	inline_base "$name" $cmd_opts || die "Failed to create inline base file"
+	inline_base "${name}" ${cmd_opts} || die "Failed to create inline base file"
 
-	{	"$EASYTLS_PRINTF" "%s\n" "# TLS crypt"
-		"$EASYTLS_PRINTF" "%s\n" ""
-		"$EASYTLS_PRINTF" "%s\n" "<tls-crypt>"
-		"$EASYTLS_CAT" "$tlskey_file"
-		"$EASYTLS_PRINTF" "%s\n" "</tls-crypt>"
-		"$EASYTLS_PRINTF" "%s\n" ""
-	} > "$inline_temp" || die "Failed to create inline file: $inline_temp"
+	{	"${EASYTLS_PRINTF}" "%s\n\n" "# TLS crypt"
+		"${EASYTLS_PRINTF}" "%s\n" "<tls-crypt>"
+		"${EASYTLS_CAT}" "${tlskey_file}"
+		"${EASYTLS_PRINTF}" "%s\n\n" "</tls-crypt>"
+	} > "${inline_temp}" || die "Failed to create inline file: ${inline_temp}"
 
 	# Use cat for its intended porpose
-	"$EASYTLS_CAT" "$inline_base" "$inline_temp" > "$inline_file"
+	"${EASYTLS_CAT}" "${inline_base}" "${inline_temp}" > "${inline_file}"
 
 	# Remove temp files
-	rm -f "$inline_base" "$inline_temp"
+	"${EASYTLS_RM}" -f "${inline_base}" "${inline_temp}"
 
 	# Hash inline file and add hash to index
 	inline_index_update add || die "Failed to update inline-index"
 
 	[ $silent_inline ] || \
-		notice "Inline TLS crypt file created: $inline_file"
+		notice "Inline TLS crypt file created: ${inline_file}"
 
 	# explicitly return success for callers
 	return 0
